### ISSUE TITLE
authenticate_entity_from_token!

### ISSUE THREAD

**Issue by ianks** [gonzalo-bulnes/simple_token_authentication#134]
When trying to authentication from a token, I am having this issue.

```
ArgumentError (wrong number of arguments (0 for 1)):
  /home/vagrant/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/bundler/gems/simple_token_authentication-2eec7464752e/lib/simple_token_authentication/token_authentication_handler.rb:2$
:in `authenticate_entity_from_token!'
```

Could you give me an example of what JSON params I would need to send in to make this work?

Currently I am attempting `{"user":{"email":"example@example.com", "authentication_token": "12345"}}`

**Comment by joelcdoyle** [comment]
I have a similar setup, and I am also confused by this behavior. If I supply wrong token/email headers I can still reach the "destroy" method. It seems like what SHOULD happen, is that if token/email headers are wrong or not provided, then the response should always be 401. That is not the case.

If, however, instead of `fallback_to_devise: false` , `fallback_to_devise: true` then I get the expected behavior. Invalid token/email headers results in 401 and correct token/email headers allows the `destroy` method to be reached.

I would like to understand it more. Shouldn't `simple_token_authentication` provide some way to define a method that will occur when token/email headers are incorrect, and simply allow restricted methods to be called when token/email headers are correct?

**Comment by gonzalo-bulnes** [comment]
Hi @joelcdoyle, please see #154, unless I'm wrong there's what you are looking for.

**Comment by joelcdoyle** [comment]
Yes, #154 explains it perfectly. Thanks!

**Comment by jpstokes** [comment]
I feel like I just about got this but I can't authentication with the email and token that I'm sending back to the server. I've tried a lot of different things at this point but haven't gotten my api to accept the  headers (X-User-Email, X-User-Token) as specified. I've created a gist will all the files I think is associated with getting this working. I'd just like to know what I need to do to get this working.

https://gist.github.com/jpstokes/e954ddb26ba3c9963852

**Comment by gonzalo-bulnes** [comment]
Hello @jpstokes,

Do you run into the error described in this issue? If not, please a new issue describing the error you got into, or the behaviour you expect and the behaviour you observe. (That's to say what you mean by your API "not accepting" the headers as long as if you are able to authenticate usets via [query params][example] for example.)

It may seem tedious, but treating a single topic per issue is important to keep the responses findable. (Remember that as well as code, issues are written once and read many times.)

  [example]: https://github.com/gonzalo-bulnes/simple_token_authentication/blob/master/README.md#authentication-method-1-query-params

Regards!

**Comment by jpstokes** [comment]
Create new issue https://github.com/gonzalo-bulnes/simple_token_authentication/issues/192
