### ISSUE TITLE
Logging in via the URL method isn't calling a sessions controller override

### ISSUE THREAD

**Issue by chriscameron** [gonzalo-bulnes/simple_token_authentication#144]
I'm seeing an issue where when logging in via a url and using an override for Devise::Sessions the create or new methods are not ever being called. 

http://localhost:3000/?account_id=1&user_email=test@test.com&user_token=token_here

Is there a way to ensure those are called? I have this in routes.rb:

```
devise_for :users, :controllers => { :registrations => 'devise_custom', :sessions => 'devise_sessions'}
```

And then a controller for the overrides to test with:

```
class DeviseSessionsController < Devise::SessionsController
  def new
    logger.info "Session New"
    super
  end

  def create
    logger.info "Session Create"
    super
  end
end
```

As I look at the simple_token_authentication source code it seems that it's not designed to ever call those. Does anyone have any suggestions on how to hook into sessions create?

**Comment by gonzalo-bulnes** [comment]
Hi @chriscameron,

You are right, _Simple Token Authentication_ does not sign in users through the Devise::SessionsController. It has been some time since you opened this issue, did you find a way to do what you wanted?

By the way, are you trying to generate some logs on signin, or was that just an example? I have nothing to suggest about hooking _Simple Token Authentication_ and the `Devise::SessionsController`, but there may be other ways to do what you want. I'm looking forward!
