### ISSUE TITLE
Does token_authenticable expires?

### ISSUE THREAD

**Issue by natonnelier** [gonzalo-bulnes/simple_token_authentication#149]
Having a mobile app getting data from our simple_token_authentication based api, it would be nice to keep the user logged in as long as he has the app open. Is it possible?

**Comment by gonzalo-bulnes** [comment]
Hello @natonnelier,

I'm not sure to understand what you want to do: do you want to keep the user logged in so the app can grab data without sending the user credentials (authentication token, email) with every request? Or do you want to make her authentication token expire in order to force her to log in again the next time she'll open the app?

**Comment by natonnelier** [comment]
hi @gonzalo-bulnes , thanks for your answer. 

I actually want to keep the user logged in, so i need authentication_token not to expire. 
Then my question is: does it expire?

**Comment by gonzalo-bulnes** [comment]
Ok. No, the authentication token does not expire, and there is no automatic renewal, so authentication tokens don't change unless you change them.

But... a successful token authentication does not, by default, sign in users in a persistent way and users credentials (authentication_token, email) are supposed to be sent with every request. You may want to use the [sign_in_token](https://github.com/gonzalo-bulnes/simple_token_authentication#configuration) option to keep users signed in. (The typical use case of that option is sending a link to sign users in automatically in a web app.) 

By the way, yours is a web app, right? Otherwise (if it were an API), I would recommend you not to use the **sign_in_token** option and provide user credentials (authentication_token, email) with each request instead.

**Comment by natonnelier** [comment]
Thanks Gonzalo. 
It's actually an API, so i would go for your advice of asking for credentials with each request.
