### ISSUE TITLE
How do I do filtering based on the controller format?

### ISSUE THREAD

**Issue by squarebing** [gonzalo-bulnes/simple_token_authentication#155]
How do I do filtering based on the controller format?

I am currently use devise, such as

before_action :authenticate_user!, only: :show, :unless => lambda{ |controller| controller.request.format.html? }

I am trying to use token authentication, but I cannot get the lambda working. Any advice?

acts_as_token_authentication_handler_for User, :only =>[:show] do |controller| not controller.request.format.html?

**Comment by gonzalo-bulnes** [comment]
Hello @squarebing,

What about:

```ruby
class ArticlesController < ActionController::Base

  acts_as_token_authentication_handler_for User
  skip_before_action :authenticate_user_from_token!
  before_action :authenticate_user_from_token!, only: :show,
    unless: lambda { |controller| controller.request.format.html? }

  # ...

end
```

The first line (`acts_as_token_authentication_handler_for User`) does two things: enable the token authentication handler behaviour in the controller, and set a before action called `authenticate_user_from_token!`. That before action is not scoped by your lambda, that's why you skip it, then re-enable it in a format that allows you to use the **unless** option. : )

The `acts_as_token_authentication_handler_for` method supports the **only** and **except** options but filters out **unless** ([source](https://github.com/gonzalo-bulnes/simple_token_authentication/blob/v1.8.0/lib/simple_token_authentication/token_authentication_handler.rb#L144)). There is no particular reason for that and I may fix it in a next release.

Note that the bang `!` method does set the Devise `authenticate_user!` as a fallback by default, that's why you don't need to set it yourself. The non-bang version (`authenticate_user_from_token`)  does not set any fallback, so you can choose.

Does that answer you question?

**Comment by gonzalo-bulnes** [comment]
Hello @squarebing,

I'm planning to add support for the `:if` and `:unless` callback options in the next release. If you have a moment, you can try the new feature by installing _Simple Token Authentication_ as follows:

```ruby
# Gemfile

gem 'simple_token_authentication', git: 'git@github.com:gonzalo-bulnes/simple_token_authentication.git', branch: 'spike-add-if-unless-filter-options'
```

Everything should then work as you first expected it to work:

```ruby
# app/controllers/some_controller.rb

acts_as_token_authentication_handler_for User, :only =>[:show], unless: lambda { |controller| controller.request.format.html? }
```

If you give it a try, I'd love to read your feedback. Regards!

**Comment by gonzalo-bulnes** [comment]
Hi @squarebing, the **v1.9.0** release is available and ships support for both the `:if` and the `:unless` ActiveSupport callbacks options. You can now define the _token authentication_ constraints just as you intended to.

Regards!
