### ISSUE TITLE
Confusing problem with acts_as_token_authentication_handler_for

### ISSUE THREAD

**Issue by npearson72** [gonzalo-bulnes/simple_token_authentication#159]
I'm using the following method but it's not working:

`acts_as_token_authentication_handler_for User, fallback_to_devise: false`

I'm still able to access the controller. When I change the fallback to true, it works but I don't want to do that given the security issues.

Any ideas why this might be happening?

**Comment by gonzalo-bulnes** [comment]
Hello @npearson72,

If by "is not working" you mean that the unauthenticated requests **do not  trigger an HTTP 401 response**, you'll find both an explanation and a demo in #154. If that were not what you meant, could you please give me more details about your application context?

Regards!

  [issue]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/154

**Comment by npearson72** [comment]
Well, what's going on is that when I send in a request without the token and email headers, it still allows it access -- this is in the case when the user is signed in. In other words, I can authenticate and I get a response with a token that I set in my cookies and then make subsequent request with. At that time the user is signed in. But if I clear my cookies and make requests, I'm still given access.

Here is my base controller:

````
class Api::V1::BaseController < ApplicationController

  acts_as_token_authentication_handler_for User, fallback_to_devise: false

  protect_from_forgery with: :null_session
  skip_before_filter :verify_authenticity_token
  before_action :require_authentication!

  private

  def require_authentication!
    throw(:warden, scope: :user) unless current_user.presence
  end
end
````

Here's what I'm passing in:

````
   "HTTP_X_USER_EMAIL"=>"null",
   "HTTP_X_XSRF_TOKEN"=>"LiMQzzg6meA+HMsI3bHfKVWQ5JU2Gc8TxjCKhYSJy8I=",
   "HTTP_X_USER_TOKEN"=>"null",
   "HTTP_ACCEPT"=>"application/json, text/plain, */*",
   "HTTP_CACHE_CONTROL"=>"max-age=0",
````

Any ideas?

**Comment by npearson72** [comment]
It seems that the session is being used. I see the session in my browser resources, and rails is tapping into it apparently to call up the `current_user` who is signed in. So even without the token and email headers, I'm able to gain access.

Is there a way to disable the session in rails completely?

If not, I modified your gem here and it does the trick, but I don't know if this was the intent:

````
def authenticate_entity_from_token!(entity)
  record = find_record_from_identifier(entity)

  if token_correct?(record, entity, token_comparator)
    perform_sign_in!(record, sign_in_handler)
  else
    sign_out current_user
  end
end
````

**Comment by gonzalo-bulnes** [comment]
Ok, I see what's going on, [this comment][null-session] may help you.

  [null-session]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/49#issuecomment-43405076

**Comment by npearson72** [comment]
Hmm, I'm confused. I'm already setting `fallback_to_devise: false`

Am I not supposed to?

**Comment by gonzalo-bulnes** [comment]
Yes, you are supposed to set `fallback_to_devise: false` in an API context. I was pointing at `protect_from_forgery_with: :null_session` to prevent eventual sessions from setting `current_user` during API requests that were unauthenticated from a "token authentication" point of view. Does that make sense to you?

**Comment by gonzalo-bulnes** [comment]
(See also [my response to the cited comment][response].)

  [response]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/49#issuecomment-43410225

**Comment by npearson72** [comment]
Ok, but I'm using `protect_from_forgery with: :null_session`. Maybe I'm just not understanding.. do you see anything in my code that I'm doing wrong?

**Comment by gonzalo-bulnes** [comment]
Oh, I was commuting and I missed that, sorry.

Remains the cookies thing. Credentials for token authentication are not meant to be sent in cookies _a priori_, and the whole point of disabling the Devise fallback is preventing cookies to be used in [CSRF attacks][csrf]. (Remember you disabled the CSRF protection for your API calls with `skip_before_filter :verify_authenticity_token` because you want anyone to be able to use your API - as long as they send authentication credentials, namely an _email_ and an _authentication token_, with every request.)

So, reading that you set your credentials in a cookie does feel not-that-right. **But**, since the Devise fallback is disabled, I see no reason right now for the eventual session data that could be stored in the cookie to be used to set `current_user`. I mean, that's supposed to be the Devise job. I'll ask for some help. (Maybe @joefiorini could have an idea?)

  [csrf]: https://en.wikipedia.org/wiki/Cross-site_request_forgery

**Comment by npearson72** [comment]
Thanks for the help. I may not have made myself very clear about the cookie thing. I'm using cookies on the client to store the token and email, but I'm sending them in the header with every request.

Should I be doing it differently?

**Comment by gonzalo-bulnes** [comment]
I'm not sure. (You didn't mention it, but: you've not enabled the **sign_in_token** option, right?)

What happens if you make a sequence of authenticated, then unauthenticated requests with two distinct users? I mean: a first authenticated request from Alice, then one from Bob, then an unauthenticated request from Alice and one from Bob?

**Comment by gonzalo-bulnes** [comment]
Hi @iobaixas, @emilioeduardob, do you have any thoughts about [what I could be happening here][1]? I can't figure out at which point the session gets persisted.

  [1]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/159#issuecomment-91078010

**Comment by npearson72** [comment]
No, I did not enable `sign_in_token`

I need to run out now, but will try to trouble shoot per your suggestion tomorrow.

**Comment by joefiorini** [comment]
@gonzalo-bulnes Sorry, my day job has taken me pretty far away from this type of work. I'm afraid I don't have the bandwidth at the moment to wrap my head around this. Good luck!

**Comment by gonzalo-bulnes** [comment]
Many thanks anyway for considering it @joefiorini. Regards!

**Comment by killerjoy** [comment]
OK not sure if this is the same as we're talking about but heres my findings...

In my API controller:

acts_as_token_authentication_handler_for User, fallback: :none

Have also tried (since the above is in the read-me but all other cases have the below, not sure if it matters): 

acts_as_token_authentication_handler_for User, fallback_to_devise: false

Then to test I open a chrome extension "postman" in this case to test API calls sending the email and auth_token with every request - works great.  Sending incorrect creds throws the proper auth errors - works great.

Now to test fallback_to_devise (or at least my understanding of it) - I open a new chrome tab and login to the webapp side of my application, which uses an application controller that does NOT acts_as_token_authentication_handler_for (only the API does).  After logged in the Devise session is open, and now if I change the credentials set in postman and request from the API the request succeeds using the session open from devise.

Does this make any sense?

**Comment by gonzalo-bulnes** [comment]
Hi @killerjoy,

Your description of the issue makes sense, and your API requests should not get authenticated via the session. I may have an idea of why this is occurring. Do you set the `authenticate_user` or `authenticate_user!` callbacks in your controllers?

The **fallback** option does only set them (by default) or not (`fallback: :none` or `fallback_to_devise: false`) when enabling the token authentication callback. If instead you do set the Devise callbacks by yourself, then the user will be authenticated by Devise when the request session makes it possible.

You can still prevent that behaviour by restricting the Devise callbacks scope to your non-API requests:

```ruby
# app/controllers/some_controller.rb

  # ...

  acts_as_token_authentication_handler_for User, fallback: :none # does not set any Devise callback
  
  # set s Devise callback for non-API requests
  before_action :authenticate_user, unless: lambda { |controller| controller.request.format.json? }

  # ...
```

Does that make sense to you?

**Note**: `fallback: :none` and `fallback_to_devise: false` are equivalent but the former is [preferred since `fallback: :exception` was introduced in **v1.10.0**][diff].

  [diff]: https://github.com/gonzalo-bulnes/simple_token_authentication/commit/66486ab2c90572eaff779af2f3debbe2564c89f7?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by gonzalo-bulnes** [comment]
Oh, @killerjoy, where are you? I'll close this issue, don't hesitate to re-open it if needed!

**Comment by AlexEmerson** [comment]
Hi there,

I probably stumble upon the same issue @ghost had a few posts above. I really hope I'm not missing something important. Here's the thing:
I have 2 parts of the application: a plain html website with parent ApplicationController:
```ruby
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    ...
end
```
and an API part under separated namespace, that utilize ApiController:
```ruby
class Api::V1::ApiController < ActionController::Metal
    protect_from_forgery
    acts_as_token_authentication_handler_for User, fallback: :exception
end
```
Considering I'm logged in on the website and have cookies with devise/warden session attached, but using the api with token based auth. You can see - no fallback to the devise, csrf protection with :null_session configured for the api controllers.

Everything works just fine with POST requests as it cleans up the devise session (due to 'protect_from_forgery'  settings).

But making a GET request to the api endpoint doesn't respond with expected 401 Unauthorized (as fallback: :exception implies) but gets normal response for authenticated user. In this case, controller authenticates user from the devise session picked from the cookies. current_user gets initialized during the request as well so it's impossible to throw unauthorized response manually as well.

Any thoughts? Thanks in advance.

**Comment by gonzalo-bulnes** [comment]
Hi @AlexEmerson,

I've found [this mention of using a separate XSRF protection mecanism][xsrf] which seems to be recommended by the Angular documentation. (I haven't read everything through yet, but it seems to me like it solves the same problem.) Any thoughts?

  [xsrf]: https://stackoverflow.com/a/15761835

**Comment by AlexEmerson** [comment]
Thanks for the response, @gonzalo-bulnes.
Maybe I wasn't clear enough, though. Actually, what I want to achieve is opposite. I have controller with
```ruby
acts_as_token_authentication_handler_for User, fallback: :exception
```
But it seems to me, that authentication still falls back to the devise session when I don't provide right X-User-Token header. And I don't have any devise's ```ruby authenticate_user!``` in my controller.

**Comment by gonzalo-bulnes** [comment]
Oh, yes, my bad.

The fallback is set, but as it's name implies, it's only a fallback for the cases when authentication fails. In this case, as you noticed, `current_user` is set before token authentication is performed. When that happens, the fallback is inhibited (it behaves like any other Devise strategy from that point of view) and the `current_user` is left untouched.

I will be unable to give you more details today, but (as a better workaround than having duplicated users) I believe that if you remove the guard in the `ExceptionFallback`, your API will be working as you expect.

```ruby
# lib/simple_token_authentication/exception_fallback_handler.rb

module SimpleTokenAuthentication
  class ExceptionFallbackHandler
    include Singleton

    # Notifies the failure of authentication to Warden in the same Devise does.
    # Does result in an HTTP 401 response in a Devise context.
    def fallback!(controller, entity)
      # throw(:warden, scope: entity.name_underscore.to_sym) if controller.send("current_#{entity.name_underscore}").nil?
      throw(:warden, scope: entity.name_underscore.to_sym) # here
    end
  end
end
```

That being said, the reference issue for this problem is #216, please let's move there to discuss possible solutions. Keeping everything related to the topic in a single issue makes easier for everyone interested to follow the updates. See also the last part of [this comment][also].

Tell me if editing the fallback does the trick, and let's discuss a permanent solution to this issue in #216!

  [issue]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/216
  [also]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/244#issuecomment-212169712

**Comment by AlexEmerson** [comment]
So I misunderstood the fallback option, now it makes sense.
#216 is definitely better place for discussion, sorry, should have found it myself.

Your code above does the trick, everything works like a charm, thank you again.
