### ISSUE TITLE
Question: using simple_token_authentication for logging in users to the payment page via e-mail link without password

### ISSUE THREAD

**Issue by feliperaul** [gonzalo-bulnes/simple_token_authentication#163]
Hi there guys,

Let's say you have a subscription model and send automatic e-mails alerting customers the subscription is about the expire. 

To reduce friction, it would be desirable that this "Click here to renew your subscription" link in the e-mail could point the user directly to the checkout page without requiring for any credentials at all.

The rationale is: If he is clicking on this link inside his email account, we don't need to ask for e-mail (obviously) and neither password, because if the email account is compromised anyone could have used "forgot my password" anyway to gain access.

So, the idea is that this "Click here to renew" would login the user and redirect him to the payment page directly, without asking for credentials.

Could this gem be used to accomplish this or I am understanding it wrong ?

**Comment by gonzalo-bulnes** [comment]
Hello @feliperaul,

You're **right**. The key here is to set the **sign_in_token** option in order to allow the session to be persisted. That should be done in an initializer, once _Simple Token Authentication_ is installed, [as described here][doc] (it's the first option in the example initializer).

  [doc]: https://github.com/gonzalo-bulnes/simple_token_authentication#configuration

You you should obtain something like:

```ruby
# config/initializers/simple_token_authentication.rb

SimpleTokenAuthentication.configure do |config|

  # Configure the session persistence policy after a successful sign in.
  config.sign_in_token = true

end
```

Once that done, your users will be able to renew their subscription after clicking a link that should look like the following one (for course it's just an example):

```html
<!-- Please do notice that you SHOULD (read MUST) use HTTPS when working with auhentication tokens /--> 
<a href="https://secure.myawesomeservice.com/subscriptions/renew?user_email=alice@example.com&user_token=1G8_s7P-V-4MGojaKD7a">
  Click here to renew your subscription
</a>
```

Once they're done with the payment, users will remain signed in until they sign out.

**Comment by gonzalo-bulnes** [comment]
Hi @feliperaul, did you succeed at allowing your users to sign in using an email link?

**Comment by feliperaul** [comment]
@gonzalo-bulnes Thanks for the awesome reply ! for some reason github never notified me and I missed it.

I'll attempt to implement this now.
