### ISSUE TITLE
Applies to ApplicationController by default?

### ISSUE THREAD

**Issue by toobulkeh** [gonzalo-bulnes/simple_token_authentication#167]
I'm working with an application that started as Rails::API and am extending it to a full rails stack.

Previously, the simple_token_authentication gem was added and the main controller didn't have any reference to it:
```ruby
class ApplicationController < ActionController::API
  include ActionController::Serialization
  # Everything that follows is for Devise compatibility
  include ActionController::RespondWith
  include ActionController::ImplicitRender

  before_action :configure_permitted_parameters, if: :devise_controller?
  respond_to :json

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

  #...

end
```

Later, I moved that `ApplicationController` to `ApiController` and re-instated the usual ApplicationController:
```ruby
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #...
```

Unfortunately, when logging into a new user type (Admin) through the default Devise Controllers -- even without Admin containing `acts_as_token_authenticatable` -- I'm receiving CSRF Exceptions:
`ActionController::InvalidAuthenticityToken in Devise::SessionsController#create`

The templates I'm using definitely have the right header meta tags for CSRF, and I don't see any special Devise config I'm not use to. I'm truly at a loss, and while it may not be this gem, this gem is the only new addition I haven't seen before.

**So I'm wondering if it gets hooked into ApplicationController by default and is there a way to skip that callback if it exists?**

I've also tried to add the controller hooks to the API controller, though I've never heard of a pattern where there addition would exclude them elsewhere.

Note that it's pinned to version 1.7.0.

Thanks!

**Comment by toobulkeh** [comment]
This was related to the use of rails-api originally. Incredibly confusion.

**Comment by gonzalo-bulnes** [comment]
Hi @toobulkeh,

To answer your question - and hopefully help you sorting out the confusion:

**No**, nothing is hooked automatically, nor by default, by _Simple Token Authentication_. In fact, that's part of the `acts_as` pattern, the behaviour of your controller(s) doesn't change until you call `acts_as_token_authentication_for SomeModel`. (And the behaviour of your model(s) doesn't change until you call `acts_as_token_authenticatable`.)


Besides, just as a note: since the gem does enforce [semantic versionning](http://semver.org), there is no need to pin a specific version (e.g. `= 1.7.0`), instead I recommend you to constrain it using `~> 1.0`. That's called a [pessimistic version constraint](http://guides.rubygems.org/patterns/#pessimistic-version-constraint) and allows to ensure that `bundle update simple_token_authentication` does update the gem as much as it is possible without breaking backward compatibility (today, that means **v1.9.0**). That works for any gem that enforces the semantic versioning convention, and for _Simple Token Authentication_ you can be sure it works because I do personally take care of naming versions accordingly.

Please don't hesitate to ask if anything remains unclear.
Regards!
