### ISSUE TITLE
Making authentication optional for public views

### ISSUE THREAD

**Issue by justinthiele** [gonzalo-bulnes/simple_token_authentication#171]
Currently, I don't require authentication for the Show and Index actions on a model. In other words:

<pre>
acts_as_token_authentication_handler_for User, except: [:show, :index]
</pre>

Users can access these pages without authenticating, but if the user has authenticated, I want to customize the page based on their user settings.

Is there a way to not require that authentication info be present but authenticate them when it is?

Thank you!

**Comment by gonzalo-bulnes** [comment]
Hi @justinthiele,

> Is there a way to not require that authentication info be present but authenticate them when it is?

Yes, that's the main purpose of `acts_as_token_authentication_handler_for User`! If an user can be authenticated from the available information, set `current_user`. Since you want that to be possible to all your controller actions, remove the `except` option.

What makes the authentication **required** is not by itself allowing the controller to handle token authentication. It is instead the fallback that is set by default in case token authentication weren't successful. (And by default that fallback is Devise `authenticate_user!`.)

To fit your scenario, you want the callback to be present except for the `show` and `index` actions:

```ruby
# disable the fallback by default
acts_as_token_authentication_handler_for User, fallback_to_devise: false
# enable it on a per-case basis
before_action authenticate_user!, except: [:show, :index]
```

If token authentication fails for one of these two actions, `current_user` won't be set.


**Note**: In case for any reason you don't want the Devise authentication strategies to be available after token authentication failed, you still can make token authentication required by replacing the `authenticate_user!` filter by the one described in #154. (In your case, with the `except: [:show, :index]` option of course.)

Tell me if that helps you!
Regards!

**Comment by justinthiele** [comment]
Ah, that makes total sense. Works like a charm now!

Really appreciate how actively you support this gem! 

:+1:
