### ISSUE TITLE
Conditionally authenticating?

### ISSUE THREAD

**Issue by rubyguy** [gonzalo-bulnes/simple_token_authentication#176]
I tried this gem and liked its simplicity. However I am facing an issue. I have already authentication set up using devise. All my web users authenticate via devise. I have an API where I want to setup token authentication only for my API user. Is there a way to conditionally use this gem to authenticate based on a flag in users table, say token_authenticable. Only users that have this flag set should be authenticated using this gem, all others should not be.

**Comment by gonzalo-bulnes** [comment]
Hi @rubyguy,

1.
If you can express your condition in your controller, then see [this comment][comment] for details about the `if / unless` options (available since **v1.9.0**).

```ruby
# app/controllers/some_controller.rb

acts_as_token_authentication_handler_for User, if: lambda { |controller| controller.condition_fullfilled? }
```

2.
But I guess your condition depends less on the controller than on the `User` instance which is trying to authenticate, and then expressing it in the controller instance may not be obvious. One way to do it could be:

```ruby
# app/controllers/some_controller.rb

# ...

private

  def condition_fullfiled?
    User.find_by(email: user_params[:email]).token_authenticatable?
  end
```

This approach has the inconvenient to closely tie your model with your controller. (What if the params you use to identify your user change? You would have to modify both the _Simple Token Authentication_ configuration **and** the `SomeController#condition_fullfiled?` method, which is not ideal. Depending on your context, that level of coupling might be acceptable, however - you are judge.)

Does this help you to make a decision? Keep me updated!



  [comment]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/155#issuecomment-91740682

**Comment by rubyguy** [comment]
@gonzalo-bulnes
Thanks for the tips. However I followed a slightly different approach. 

1. I set the authentication_token to " " (single space) in before_save callback in my User model if a user has token_authenticable flag as false. This way simple_token_authentication gem does not create a new token and users cannot log in using this authentication. They can however log in using the normal webpage login which is exactly I wanted. When ever I want to enable API login for a user, all I do is set the flag to true in there database record using a checkbox from my admin page, and the gem will populate a new token which can be used to log in via API. This works great! Thanks for this great gem!

It will be great if you can incorporate the #1 in your next release. I think lot of users who are already using devise and want to selectively enable API login will find it extremely useful

2. I changed the API login method to username using config/initializers/simple_token_authentication.rb file as suggested in your gem's documentation. Works perfectly. Thanks again!

3. I changed the persistence to true using config.sign_in_token = true flag in this file. But I don't have a way to test this via curl. What is the best way to test this?

**Comment by thomasdarde** [comment]
Hi @rubyguy authentication_token set to " " will not lead to token "%20" to be accepted ?

**Comment by Fire-Dragon-DoL** [comment]
This should definitely be moved to the wiki, it's extremely helpful

**Comment by gonzalo-bulnes** [comment]
Hi @Fire-Dragon-DoL,

I started creating wiki pages a few dsys ago to address #96, and particularly to answer @ssurfr2819 questions. I'm not sure that you can edit the wiki right now, but if you can, please feel free to create a new page about **authenticating conditionally**. If you can't, I will. Anyway, many thanks, the wiki task is huge, and that kind of feedback is really useful!

Best!

**Comment by Fire-Dragon-DoL** [comment]
@gonzalo-bulnes If I'm allowed, I would love to do that. I'm experimenting with the conditional authentication right now and it's working fine

**Comment by gonzalo-bulnes** [comment]
Hi @Fire-Dragon-DoL,

I've checked, and you should be able to edit the wiki, so please, go ahead! : )

**Comment by Fire-Dragon-DoL** [comment]
@gonzalo-bulnes great, I'll start from monday though, tomorrow I'm traveling for whole day ;)

**Comment by Fire-Dragon-DoL** [comment]
@gonzalo-bulnes thanks, here you are: https://github.com/gonzalo-bulnes/simple_token_authentication/wiki/Conditionally-authenticate-with-Simple-Token-Authentication feel free to move it around/play with it

**Comment by gonzalo-bulnes** [comment]
Thank you @Fire-Dragon-DoL!
