### ISSUE TITLE
ParseError

### ISSUE THREAD

**Issue by ianpgo** [gonzalo-bulnes/simple_token_authentication#186]
Hey great work on the gem. I understand how it works but I'm having problem making JSON requests to my rails api app when creating a new user.
If I signup and create a new user from the internal client it works. 

When I make an external json request though (for example on postman or on curl) i get and error, specifically this ActionDispatch::ParamsParser::ParseError. But it seems to me that I am making my requests correctly. I'll attach the rails error on this post. 

Is there something I have to enable to allow external clients to make requests?

![screen shot 2015-08-07 at 3 39 29 pm](https://cloud.githubusercontent.com/assets/4734313/9144417/c7c56ba0-3d1a-11e5-8bfc-af87a44c7ffe.png)

**Comment by thiagogsr** [comment]
Hi,

I think it is not a gem problem. Please try send params as url params, maybe clicking at 'Params'.

```sh
$ curl -X POST http://localhost:3000/players/sign_up?email=test3@test.com&password=12345678
```

**Comment by gonzalo-bulnes** [comment]
Hello @ianpgo,

I can confirm the issue has no relation with _Simple Token Authentication_. [ActionDispatch][intro] gets involved before your request even hits the Rails router. (I'm sorry, the link is a bit old, but ActionDispatch is no longer mentioned on newer guides. It's role hasn't changed since anyway.)

  [intro]: http://guides.rubyonrails.org/v3.2.13/getting_started.html#the-components-of-rails

Are you sure to be sending JSON requests through your client? And in that case, are you sure that you set the corresponding headers appropiately?

**Comment by ianpgo** [comment]
Thanks for the help. I ended up separating the Users and Player models in my app and everything worked out fine!

**Comment by gonzalo-bulnes** [comment]
Ok, I'm glad you found a solution : )
