### ISSUE TITLE
Q: Can I use this gem with omniauth-facebook? (A: Yes!)

### ISSUE THREAD

**Issue by ianchen06** [gonzalo-bulnes/simple_token_authentication#187]
Hi there thanks for the great gem. I have a web app with Grape API and ReactJS frontend.

My application requires both Devise user login as well as `omniauth-facebook` login.

Is that doable with this gem? Post to regular devise omniauth path and receive a session and a token back?

Thanks a lot!

**Comment by gonzalo-bulnes** [comment]
Hello @ianchen06!

I think there should be no problem with using any OAuth strategy to login (and/or Devise database authenticatable strategy), as soon as you ensure that your controller does include the user _authentication token_ in the response (as described in [here][info] - what's true for a mobile app should be true for your ReactJS app).

  [info]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/185#issuecomment-128560442

The "get the authentication token back" part is on your side, but once that done, _Simple Token Authentication_ does provide means for your API controllers to authenticate users without having to store and send their passwords in/from the ReactJS clients.

You're using Grape! : )
There is a Grape adapter available, which I haven't released because I want someone familiar with Grape (or two!) to review it.
If you want to give it a try, I described how you can do it in [this comment][grape] a while ago. Let me know if you want me to update the branch, so you can get the latest features, that's something I'd love to release : )

  [grape]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/138#issuecomment-91102970

**Comment by pywebdesign** [comment]
Omniauth-facebook + this gem work like a charm!

**Comment by gonzalo-bulnes** [comment]
Hi @pywebdesign!

That's good to know! I started populating the [wiki](https://github.com/gonzalo-bulnes/simple_token_authentication/wiki). If you feel like adding a page about this, feel free to do it. (And if you don't feel like it, please feel free not to!)
Cheers!

**Comment by pywebdesign** [comment]
It really boils down to following the installation instruction on devise, then omniauth-facebook and then simple_token_authentication. Everything falls in place nicely!

**Comment by gonzalo-bulnes** [comment]
Ok, thank you for the detaills @pywebdesign : )

**Comment by micahlisonbee** [comment]
Is there an example implementation of devise + simple_token_authentication + omniauth-facebook (any any omniauth strategy) somewhere?

**Comment by aqabawe** [comment]
@gonzalo-bulnes sorry to bring up an old issue again, is the grape adapter mentioned merged?

**Comment by gonzalo-bulnes** [comment]
Hi @aqabawe! It's all good, issues are there to be useful : )

A work in progress for the Grape adapter is waiting for someone to [try it and give feedback on it](https://github.com/gonzalo-bulnes/simple_token_authentication/issues/138#issuecomment-263721468). If you're keen on doing that, I'm happy to help with the troubleshooting. (You'll find more of the context in https://github.com/gonzalo-bulnes/simple_token_authentication/issues/138, and https://github.com/gonzalo-bulnes/simple_token_authentication/issues/194.) 

I don't use much Grape myself and you insight would be very much appreciated. On the other side, if you need a hand figuring out how to test the gem directly from the branch, let me know and I can give you a hand.
