### ISSUE TITLE
setting token handler for Devise Controllers

### ISSUE THREAD

**Issue by jsanders67** [gonzalo-bulnes/simple_token_authentication#190]
I am trying to create an application with a front end as well as a RESTful API, but cannot get my registration controller that is inheriting from my devise controller to redirect me when I try to access a method that should require token authentication 

this is my routes.rb file
```
      devise_scope :user do
          post 'users/login' => 'sessions#create', :as => :login
          delete 'users/logout' => 'sessions#destroy', :as => :logout
          post 'users/register' => 'registrations#create', :as => :register
          delete 'users/delete_account' => 'registrations#destroy', :as => :delete_account
          get 'users' => 'registrations#index'
      end
```

This is my controller
```
class Api::RegistrationsController < Devise::RegistrationsController

	#skip_before_filter :verify_authenticity_token
	acts_as_token_authentication_handler_for User, only: [:index]

	def create
		render json: { status: "complete" }
	end

	def index
		render json: { status: "shouldnt get here" }
	end

end
```

Note that the GET index method for users is just to test a method that should be rerouted. Has anyone had this issue as well or know a solution to it?
I also want to know if there is a way to respond_to json with json instead of html body on GET request

**Comment by gonzalo-bulnes** [comment]
Hi @jsanders67,

Here is an [explanation](https://github.com/gonzalo-bulnes/simple_token_authentication/issues/154#issuecomment-75821695) for the behaviour you observe. Since sessions are not persited in API, there is usually no much point in redirecting requests which failed authentication on your API controllers; however, you can restrict access to them using the **fallback** option to throw an exception, see #174 for examples.

**Note**: _Simple Token Authentication_ does fallback to Devise by default. If you disable the CSRF protection (`skip_before_filter :verify_authenticity_token`), make sure to disable the Devise fallback ([documentation][doc])!

  [doc]: https://github.com/gonzalo-bulnes/simple_token_authentication/tree/v1.10.0#integration-with-other-authentication-and-authorization-methods

About rendering JSON, I find the [Rails Guides section dedicated to rendering][json] useful.

  [json]: http://guides.rubyonrails.org/layouts_and_rendering.html#using-render

Best!
