### ISSUE TITLE
Ability to determine if token is valid?

### ISSUE THREAD

**Issue by statespindle** [gonzalo-bulnes/simple_token_authentication#191]
Is there the ability to determine if the token is valid (other than look up the user again via the key)?  For instance, checking that the token is correct in an after_ or before_ action?

**Comment by gonzalo-bulnes** [comment]
Hi @statespindle,

I'm not sure to understand what you want to do, but the authentiation tokens are randomly generated (see [`SimpleTokenAuthentication::TokenGenerator`][generator]) and have no specific validity rule on their own. (See also [`Devise.friendly_token`][friendly_token] and [`SecureRandom.urlsafe_base64`][random]).

A string is considered as a correct authentication token when it _compares_ successfully with the authentication token which was stored for a given user. You can perform that comparison anytime you want, I'd only recommend you to:

1. Only compare authentication tokens using a function designed to prevent [timing][timing] [attacks][attacks] (see [`SimpleTokenAuthentication::TokenComparator`][comparator], see also [`Devise.secure_compare`][compare]
1. Do not fetch the user record from the database using the authentictation token as key, for the same reason. Use any other identifier instead (_Simple Token Authentication_ uses the user **email** by default, but you can [change it][identifier]).

About performing the comparison in an ActiveRecord callback (`before_action`, `after_filter`...), it's not only possible, but that's in fact what `acts_as_token_authentication_handler_for User` does. ([source][callback], [details][callback_details]) That part of the code may be a bit difficult to read because it handles a variable record name (e.g. `user` or `admin`), I can walk you through it if needed, don't hesitate to ask!)

  [callback]: https://github.com/gonzalo-bulnes/simple_token_authentication/blob/v1.10.0/lib/simple_token_authentication/token_authentication_handler.rb#L100
  [callback_details]: https://github.com/gonzalo-bulnes/simple_token_authentication/blob/v1.10.0/lib/simple_token_authentication/token_authentication_handler.rb#L144-L151

  [generator]: https://github.com/gonzalo-bulnes/simple_token_authentication/blob/v1.10.0/lib/simple_token_authentication/token_generator.rb#L5-L7
  [friendly_token]: https://github.com/plataformatec/devise/blob/v3.5.2/lib/devise.rb#L464-L471
  [random]: http://ruby-doc.org/stdlib-2.2.2/libdoc/securerandom/rdoc/SecureRandom.html#method-c-urlsafe_base64
  [comparator]: https://github.com/gonzalo-bulnes/simple_token_authentication/blob/v1.10.0/lib/simple_token_authentication/token_comparator.rb#L6-L18
  [compare]: https://github.com/plataformatec/devise/blob/v3.5.2/lib/devise.rb#L473-L481
  [timing]: https://gist.github.com/josevalim/fb706b1e933ef01e4fb6#file-2_safe_token_authentication-rb-L17-L22
  [attacks]: https://en.wikipedia.org/wiki/Timing_attack
  [identifier]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/68
