### ISSUE TITLE
Sending request with headers but getting 401 Unauthorized back.

### ISSUE THREAD

**Issue by jpstokes** [gonzalo-bulnes/simple_token_authentication#192]
I'm sending the headers: X-User-Email and X-User-Token, but the request is coming back as 401 not authorized. I've created a gist will all the files I think is associated with getting this working. I'd just like to know what I need to do to get this working. Thx.

https://gist.github.com/jpstokes/e954ddb26ba3c9963852

**Comment by gonzalo-bulnes** [comment]
Hi @jpstokes,

Your `ApplicationController` does define the Devise callback `before_filter authenticate_user!`. That callback is inherited by your `Api::ApplicationController` which in turn enables token authentication.
Because the Devise callback was defined first, the Devise exception is raised before _Simple Token Authentication_ even fetches your request headers.

Unless I'm wrong, and assuming that the headers are correct, removing that callback from `ApplicationController` ([source][src]) should allow token authentication to be performed and solve your issue. _Simple Token Authentication_ [defines the Devise fallback by default][default], but you probably want your API controllers to disable it and [raise an exception when token authentication fails][exception] (**TL;DR**: `fallback: :exception`).

On the other hand, you probably want your non-API controllers to enable the Devise authentication methods. Do not forget to re-define the Devise callback somewhere, just be sure it does not get inherited by your API controllers. (Maybe authentication-related callbacks could be extracted to their own module or concern?)

In case of success, your API controller should trigger a 401 error on missing or incorrect token authentication credentials (headers or query params) and should set `current_user` if credentials are right. The non-API controllers on the other hand should ignore totally the token authentication headers or query params. (If it's not the behaviour you want, tell me, we can iterate on this.).

  [default]:https://github.com/gonzalo-bulnes/simple_token_authentication/tree/v1.10.0#integration-with-other-authentication-and-authorization-methods
  [exception]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/154
  [src]: https://gist.github.com/jpstokes/e954ddb26ba3c9963852#file-base_application_controller-rb-L7

Regards!

**Comment by jpstokes** [comment]
I appreciate the quick and thorough feedback...I'll let you know how it goes.

**Comment by jpstokes** [comment]
Many thanks that was the problem.

**Comment by gonzalo-bulnes** [comment]
You're welcome @jpstokes. I'll edit a little bit the title and close the issue, ok?
