### ISSUE TITLE
Rspec test scenario not authenticating.

### ISSUE THREAD

**Issue by oscarsiniscalchi** [gonzalo-bulnes/simple_token_authentication#202]
Hi! First of all, very nice gem!
I am having an issue testing my implementation and I am looking forward to see if someone have experience testing this gem with rspec and if it is any extra consideration to do.

This is what I have

`base api controller`
```
module Api
  class BaseController < ApplicationController
    protect_from_forgery with: :null_session
    skip_before_action :verify_authenticity_token, if: :json_request?
  end
end

```
`Controller with an endpoint to display the user data (auth token, email etc)`
```
module Api
  class UsersController < Api::BaseController
    acts_as_token_authentication_handler_for User, fallback: :devise

    def user_data
      @user = current_user
    end
  end
end
```

`I am trying to test this with this`
```
require 'rails_helper'

RSpec.describe Api::UsersController, type: :controller do
  describe '#user_data' do
    context 'for authenticated users' do
      it 'should be ok' do
        user = create :user
        get :user_data, user_email: user.email, user_token:  user.authentication_token, format: :json
        expect(response.status).to eq(200)
      end
    end
  end
end
```

My problem is this is returning a 401 status instead. I try and it does work when I use the feature on my localhost.

Any idea? or something that I may be missing/doing wrong?

**Comment by gonzalo-bulnes** [comment]
Hello @oscarsiniscalchi,

I would first check if `user.authentication_token.nil?` in your RSpec example.

Why?
Because when your `user` is created, its authentication token is probably `nil` - I say _probably_ because that depends on the factory you're using. But there is no reason for the factory to set the authentication token anyway (it is not a required attribute).

When `user.authentication_token.nil?`, a new authentication token is generated automatically on `user.save` (see [this section][doc] of the documentation).

There are a lot of reasons to update (and `save`) users in development environment, but not that much in a test environment. That's why in your spec, `user` may just have no authentication token yet.

  [doc]: https://github.com/gonzalo-bulnes/simple_token_authentication/tree/v1.10.1#tokens-generation

If I'm right, making sure the user is saved before performing the request should solve the issue.

```ruby
require 'rails_helper'

RSpec.describe Api::UsersController, type: :controller do
  describe '#user_data' do
    context 'for authenticated users' do
      it 'should be ok' do
        user = create :user

        # Temporary: if my hypothese is right, then this expectation should fail. (Once verified, remove these two lines.)
        expect(user.authentication_token).not_to be_nil

        user.save # generate the user authentication token

        get :user_data, user_email: user.email, user_token:  user.authentication_token, format: :json
        expect(response.status).to eq(200)
      end
    end
  end
end
```

Keep me updated!

**Comment by gonzalo-bulnes** [comment]
Hi @oscarsiniscalchi,

Did you succeed testing authentication in your `Api::UsersController#user_data` method?
