### ISSUE TITLE
Devise master support ?

### ISSUE THREAD

**Issue by FPierre** [gonzalo-bulnes/simple_token_authentication#213]
The Gem has a dependency on Devise >= 3.2

Is it possible to use it with the Master version of Devise ?

**Comment by chrisvel** [comment]
+1

**Comment by FPierre** [comment]
I forked the projet and modifiy the gemspec to allow any version of Devise. It's work!

**Comment by gonzalo-bulnes** [comment]
Hello @FPierre (and @chrisvel),

Devise [3.2][versions] is supported and so do any 3.x current or future version (that's what [`"devise", "~> 3.2"`][version-constraint] means). It is reasonable to support future 3.x releases because Devise (like _Simple Token Authentication_) enforces [semantic versionning][semver], which means that backward compatibility will be ensured for the whole 3.x series.

However, at some point, the Devise's `master` branch will reflect work on the first 4.x release, which -[by definition][semver]- will introduce a breakage in backward compatibility. Since Devise 4.0.0 hasn't yet been released, the way in which backward compatibility will be broken is yet unknown, and _Simple Token Authentication_ cannot reasonably support it now.

However, as long as Devise's `master` branch will keep reflecting work on the 3.x series, it's unlikely to cause trouble with _Simple Token Authentication_, and what you did -loosen the version constraint in your fork- is the right way to go. If doing so you notice what seems to be an uncompatibilty, you're welcome to open an issue here - while I can't support it formally, I'd be glad to help you dealing with issues if I can.

Best regards!

  [versions]: https://rubygems.org/gems/devise/versions
  [version-constraint]: https://github.com/gonzalo-bulnes/simple_token_authentication/blob/v1.12.0/simple_token_authentication.gemspec#L21
  [semver]: http://semver.org/
