### ISSUE TITLE
Rails 5 support?

### ISSUE THREAD

**Issue by chrisvel** [gonzalo-bulnes/simple_token_authentication#214]
I am getting lots of errors when running Rails commands, as `rails server` and `rails db:migrate`. It is important to know that there is Rails 5 support. I've checked with devise 4 and 3.5.5 - 4 doesn't work at all while 3.5.5 shows lots of error messages. I tried to hack this around but failed hard:

`DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /home/willy/my-api/config/application.rb:7)
`

**Comment by gonzalo-bulnes** [comment]
Hello @chrisvel,

That one is a Devise issue ([source][issue]), unrelated with _Simple Token Authentication_. Please refer to the Devise's [issues tracker][comment].

That being said, I'm very interested in knowing about any potential _Simple Token Authentication_ issues with the future Rails 5 release. If you want to contribute, don't hesitate to re-open this issue to report your findings so we can draft ahead the Rails 5 support! : )

Best! 

  [issue]: https://github.com/plataformatec/devise/issues/3879
  [comment]: https://github.com/plataformatec/devise/issues/3879#issuecomment-168376663

**Comment by chrisvel** [comment]
@gonzalo-bulnes thanks.

https://rubygems.org/gems/devise/versions/4.0.0.rc1

**Comment by gonzalo-bulnes** [comment]
@chrisvel Refering to [your comment][comment]: it would be great if you could describe the issues you're finding when using _Simple Token Authentication_ with Devise 4.

That would allow us to sort them and figure out what's necessary to implement support for both Devise 4 and Rails 5, and would be a good contribution.

@u007 Any help would be greatly appreciated!

  [comment]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/221#issuecomment-181540535

**Comment by chrisvel** [comment]
Actually this is the issue that I have described that appears several times. I don't know how else could I help.

**Comment by bublik** [comment]
+1

**Comment by gonzalo-bulnes** [comment]
Hi @chrisvel, @bublik,

As far as I know, at this point Rails 5 support does no longer present particular issues (details below).

In the [`spike-add-rails-5-support`][compare] branch (experimental) I used **Devise 4.0.0.rc2** and **Rails 5.0.0.beta3** to build [this example application][demo].

Learnings (details in the commit messages):

  - Devise 4.0.0.rc2 drops support for Ruby 1.9.3
  - the Rails 5.0.0.beta3 dependencies require Ruby 2.2.2 at least
  - Mongoid won't support Rails 5 until Mongoid 6 is released

If you're not using Mongoid, everything should be fine with the `spike-add-rails-5-support` version.

To conclude: I'll keep a look on Mongoid 6, and I don't exclude releasing partial Rails 5 support if it is not released when Rails and Devise are ready.

**Note**: @gabrielc63 I did put part of [your PR][pr] on hold to fix the `qualified_const_defined?` warning. I plan to use it, but since there is already a lot to move around, I'll wait the Rails 5.1 release to do it. (Thank you!)

  [compare]: https://github.com/gonzalo-bulnes/simple_token_authentication/compare/spike-add-rails-5-support
  [demo]: https://github.com/gonzalo-bulnes/rails-5-token-authentication-demo
  [pr]: https://github.com/gonzalo-bulnes/simple_token_authentication/pull/229

**Comment by chrisvel** [comment]
@gonzalo-bulnes seems it's working now, except a warning:

`DEPRECATION WARNING: Module#qualified_const_defined? is deprecated in favour of the builtin Module#const_defined? and will be removed in Rails 5.1. (called from adapter_dependency_fulfilled? at /home/user/.rvm/gems/ruby-2.3.0/bundler/gems/simple_token_authentication-33eea208e498/lib/simple_token_authentication.rb:49)`

which seems harmless but should be taken care of.

**Comment by gonzalo-bulnes** [comment]
Hi @chrisvel,

Taking care of the warnings is part of the note I wrote to @gabrielc63.

Thank you for your feedback! I'll make sure we're ready to release when Rails 5 is released.

Also, please note that it is will be a major release because of the drop of support to Ruby 1.9.3 - you should expect to change your `Gemfile`to:

```ruby
# Gemfile

gem 'simple_token_authentication', '~> 2.0'
```

I may write a formal `CHANGELOG` for that occasion. If I do, I'll announce it in a separate issue.

Let me know if you find anything in the next few weeks that I may have missed relative to Rails 5 support!

**Comment by gonzalo-bulnes** [comment]
Hi @chrisvel,

I figured out that Rails 5 support can be added without breaking backward compatibility. I explored that possibility in [`spike-add-rails-5-support-without-backward-compatibility-breakage`][compare] (experimental and drafty) and tested it with Rails 4 and 5.0.0.beta3. It seems fine to me.

  [compare]: https://github.com/gonzalo-bulnes/simple_token_authentication/compare/spike-add-rails-5-support-without-backward-compatibility-breakage?expand=1

Because pre-release versions are omitted by Bundler unless explicitly required, at this point it is not possible to test both Rails 4 and Rails 5 with the same code, but if you (or @bublik, @gabrielc63) want to try it, you can use:

```ruby
# Gemfile

# Rails 5.0.0.beta3 and Devise 4.0.0.rc2 - Mongoid unsupported
gem 'simple_token_authentication', git: 'https://github.com/gonzalo-bulnes/simple_token_authentication.git', branch: 'spike-add-rails-5-support-without-backward-compatibility-breakage', ref: '090ad57392b06fa1defbb70e8faa04fda99d5db1'

# or
# any Rails 4 and Devise 3
gem 'simple_token_authentication', git: 'https://github.com/gonzalo-bulnes/simple_token_authentication.git', branch: 'spike-add-rails-5-support-without-backward-compatibility-breakage', ref: 'c59431f33d51c96bb1e942d849253c771cb85d5b'
```

By the way, this will finally **not** be a major release, but a minor one (I'm glad of that) and the usual gem requirement will keep being just fine:

```ruby
# Gemfile

gem 'simple_token_authentication', '~> 1.0'
```

Also, shipping a pre-release version before the Rails 5 release is available would be tricky because of the temporary pinning of the Rails-related and Devise dependencies. But I'll release this as soon as Rails 5.0.0 is available.
I don't want to commit to a version number before that, because the Rails release [may take some time][blog]), but it will probably be **v1.13.0**.

Meanwhile, feedback or comments about anything missing or not behaving as expected are welcome!

Thanks!

  [blog]: http://weblog.rubyonrails.org/2016/2/27/Rails-5-0-beta3/

**Comment by chrisvel** [comment]
@gonzalo-bulnes thanks for your detailed reply. All seem to be working fine now. :)

**Comment by gonzalo-bulnes** [comment]
I'll keep this open until the Rails 5 support is released.

**Comment by gonzalo-bulnes** [comment]
Update: [`ActiveController#env` is also deprecated in Rails 5][ref], I updated the experimental branch with a fix kindly provided by @fighterii. 

  [ref]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/237#issuecomment-205855283

**Comment by aried3r** [comment]
Seeing as [Devise 4.0.0 is released](https://github.com/plataformatec/devise/blob/master/CHANGELOG.md#400---2016-04-18), will support for it be added before Rails 5 compatibility? I'd love to upgrade Devise even before switching to Rails 5. :)

**Comment by EppO** [comment]
@aried3r: please check the fork I've just made: https://github.com/gonzalo-bulnes/simple_token_authentication/pull/243
it's based on @gonzalo-bulnes's experimental branch for Devise 4/Rails 5 support

**Comment by gonzalo-bulnes** [comment]
Hi @aried3r, @EppO,

I think I can do that, I'll confirm in the next few days - I've to check what it means in terms of test suite, but with the [brand new build matrix][matrix] it should be easy to set up.

For clarity, let's discuss the details in #245.

  [matrix]: https://github.com/gonzalo-bulnes/simple_token_authentication/blob/master/CHANGELOG.md#unreleased

**Comment by silva96** [comment]
Hi, since mongoid 6 support is not ready I added postgres and activerecord along with mongoid
where activerecord would be only for authentication and all of business models will still be mongoid.

the problem is it isn't working
 
I added the gem using the branch 'spike-add-rails-5-support'. which apparently doesn't have mongoid support. But I don't need mongoid support, it is just the default orm I use for business models. simple_token_authentication is trying to load the adapter since it finds it registered in my app I believe. How do I explicitly tell simple_token_authentication gem to work using active_record.

```
/box/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- simple_token_authentication/adapters/mongoid_adapter (LoadError)
web_1    | 	from /box/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `block in require'
web_1    | 	from /box/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:259:in `load_dependency'
web_1    | 	from /box/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
web_1    | 	from /box/bundler/gems/simple_token_authentication-f1a672d6493f/lib/simple_token_authentication.rb:36:in `block in load_available_adapters'
web_1    | 	from /box/bundler/gems/simple_token_authentication-f1a672d6493f/lib/simple_token_authentication.rb:34:in `collect'
web_1    | 	from /box/bundler/gems/simple_token_authentication-f1a672d6493f/lib/simple_token_authentication.rb:34:in `load_available_adapters'
web_1    | 	from /box/bundler/gems/simple_token_authentication-f1a672d6493f/lib/simple_token_authentication.rb:52:in `<module:SimpleTokenAuthentication>'
web_1    | 	from /box/bundler/gems/simple_token_authentication-f1a672d6493f/lib/simple_token_authentication.rb:6:in `<top (required)>'
web_1    | 	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
web_1    | 	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
web_1    | 	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
web_1    | 	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
web_1    | 	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
web_1    | 	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
web_1    | 	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
web_1    | 	from /app/config/application.rb:16:in `<top (required)>'
web_1    | 	from /box/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:88:in `require'
web_1    | 	from /box/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:88:in `block in server'
web_1    | 	from /box/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:85:in `tap'
web_1    | 	from /box/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:85:in `server'
web_1    | 	from /box/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
web_1    | 	from /box/gems/railties-5.0.0.rc1/lib/rails/commands.rb:18:in `<top (required)>'
web_1    | 	from bin/rails:4:in `require'
web_1    | 	from bin/rails:4:in `<main>'
```

**Comment by gonzalo-bulnes** [comment]
Yep, the reference branch for Rails 5 support is `spike-add-rails-5-support-without-backward-compatibility-breakage`, see https://github.com/gonzalo-bulnes/simple_token_authentication/issues/214#issuecomment-202359541 (a couple of comments below the one which mentioned `spike-add-rails-5-support`).

There were [quite relevant changes after the first review we did on `spike-add-rails-5-support`](https://github.com/gonzalo-bulnes/simple_token_authentication/issues/214#issuecomment-202359541) and the change of strategy made irrelevant to keep updating that branch. I'll put a note in the corresponding comment to make that clear.

**Comment by gonzalo-bulnes** [comment]
[Rails 5 is out!](http://weblog.rubyonrails.org/2016/6/30/Rails-5-0-final/) :D
I'll release this as soon as I can.

**Comment by gonzalo-bulnes** [comment]
> Yes, Mongoid 6 is waiting for Rails 5 as well = ) -- ([source](https://jira.mongodb.org/browse/MONGOID-4293?focusedCommentId=1309702&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1309702))

Mmm, I'll wait a few days to see if the Mongoid team releases Mongoid 6. If not, I'll release the Rails 5 support without Mongoid, as previously announced.

**Comment by gonzalo-bulnes** [comment]
Meanwhile, I created a new experimental branch to support the Rails 5 release ([`spike-add-rails-5-support-without-Mongoid-support`][compare]). 

**Note**: That branch is just an updated version of `spike-add-rails-5-support-without-backward-compatibility-breakage`, and provides no support for Mongoid. Ouside of that, everything should run smoothly on Rails 5. Please report here any issue using it so I can integrate any required change in the correponding release.

```ruby
# Gemfile

# Rails 5 and Devise 4 - Mongoid unsupported
gem 'simple_token_authentication', git: 'https://github.com/gonzalo-bulnes/simple_token_authentication.git', branch: 'spike-add-rails-5-support-without-Mongoid-support', ref: '0f236983914c76ac55b8bf332b70ec4fb1572dae'
```

(@alex-sysoev, @ljubomirm, @taintedzodiac)

  [compare]: https://github.com/gonzalo-bulnes/simple_token_authentication/compare/master...spike-add-rails-5-support-without-Mongoid-support

**Comment by gonzalo-bulnes** [comment]
Hi everyone!

Rails 5 support is now available in `master`, [I'll release it in the next few days](https://github.com/gonzalo-bulnes/simple_token_authentication/blob/master/CHANGELOG.md). Meanwhile, please reopen this issue if you find any... issue. I don't expect any, but still have to perform the final review.

Thanks for your help, particularly @chrisvel for getting this started.

**Comment by gonzalo-bulnes** [comment]
The **v1.14.0** release it out! The [demo application](https://github.com/gonzalo-bulnes/rails-5-token-authentication-demo) is up to date too, while pretty basic, it may be useful.

 Again, thank you everyone in this thread.
