### ISSUE TITLE
When I am sign in with browser, token isn't required.

### ISSUE THREAD

**Issue by rubydev** [gonzalo-bulnes/simple_token_authentication#216]
1. I login to service with browser.
2. Open any REST API endpoint in the browser.
3. Browser loads and shows JSON response.

What I expect:
This must not work for any endpoint. It's forbidden without X-User-Token. 

How can I set it?

**Comment by gonzalo-bulnes** [comment]
Hi @rubydev,

It seems to me that this is an **authorization** issue (see the first paragraph of [this comment][comment] for a distinction between _authorization_ and _authentication_). That's why I would recommend that you use two different users: one for the API endpoints whose access is particularly restricted, another to sign in people via other strategies. Each person would have two sets of credentials, respresented by two Devise users (e.g. Alice can use the application in a browser by loging in as `"alice"` and use the API sending the credentials of `"alice-API"`).

Another idea to do so could be using a **before_token_authentication** hook to identify requests that were token authenticated. There is no support for such hooks as of **v1.12.0**, but [this issue][hooks] gathers several ideas which go in that direction. If you like the hooks idea, contributions are welcome!

  [comment]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/173#issuecomment-108023563
  [hooks]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/217
