### ISSUE TITLE
Some things to add to documentation

### ISSUE THREAD

**Issue by wjdhamilton** [gonzalo-bulnes/simple_token_authentication#223]
Hello,

May I respectfully suggest that you add a few basics into the current docs around how to properly configure the app beyond the gem's immediate concerns? It would be very helpful to those of us who are less experienced if, for instance, it was noted that the application controller should include `respond_to :json` (I was surprised I had to add this at all - I'm using the RailsAPI gem and inheriting from `ActionController::API`). Also, could a few examples of integration tests be added? The reason I ask is that I had to spend some time looking about to find out what the correct parameters for `#sign_in` are. So an example for `#sign_in`, `#sign_out` as well as the current set of tests you've already posted would be great, and perhaps smooth the way for those of us who are new to this setup!

Many thanks,

James

**Comment by gonzalo-bulnes** [comment]
Hello @wjdhamilton,

As mentionned in the Documentation section of the `README`, the closed issues are organized as a [FAQ][faq]. You'll find there pointers to get started. In particular, see #45 and [the references to this tutorial][tutorial].

About **integration testing**:

_Simple Token Authentication_ itself was tested using Cucumber until **v1.5.1**. In #46 you'll find a description of the Cucumner setup that was used to test the gem behaviour, and you can browse the resulting documentation [in the corresponding Travis CI build][travis].

The approach was quite verbose to test the gem itself, because multiple frameworks and configurations must be covered, that's why I changed it when adding support for Rails::API. I would recommend that approach, however, to ensure that an application behaves as expected. The resulting scenarios can be written in an user-oriented way and the resulting documentation made very readable. Don't hesitate to comment in #46 if needed.

Also, you'll find some starting points about testing your API with RSpec and Minitest in [the corresponding wiki page][wiki].

Of course, all that can certainly be improved, and contributions are very welcome!

  [wiki]: https://github.com/gonzalo-bulnes/simple_token_authentication/wiki/Testing
  [faq]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues?q=is%3Aclosed+sort%3Acomments-desc+label%3Aquestion
  [travis]: https://github.com/gonzalo-bulnes/simple_token_authentication/tree/v1.5.1#executable-documentation
  [testing]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/46
  [tutorial]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/45#issuecomment-38810391
