### ISSUE TITLE
devise after_database_authentication callback

### ISSUE THREAD

**Issue by reaper** [gonzalo-bulnes/simple_token_authentication#226]
Hi, quick question, do you implemented a callback to add in the token authenticatable model to execute code when user has been authenticated ?

As the after_database_authentication devise authentication callback.

Thank you

**Comment by gonzalo-bulnes** [comment]
Hello @reaper,

The discussion around implementing callbacks/hooks as part of the _Simple Token Authentication_ API is happening in #217.

While I'm pretty convinced that would be a useful feature, the main point now is to define which callbacks to implement and what names to use in order to make their use as intuitive as possible for Devise users.

That should not be such a big deal, I'd like to move on and would be greatful for feedback on #217!

**Comment by gonzalo-bulnes** [comment]
Hi @reaper, just in case you didn't follow the discussion in the other issue, the `after_successful_token_authentication` hook is available since **v1.15.0**!
