### ISSUE TITLE
Several token authenticatable models in same controller - works only the last

### ISSUE THREAD

**Issue by lemboy** [gonzalo-bulnes/simple_token_authentication#242]
```

module Properties
  class Api::V1::TransfersController < Api::V1::ApplicationController

    acts_as_token_authentication_handler_for ::Property, fallback: :none
    acts_as_token_authentication_handler_for ::SuperProperty
    ...
end
```
Successful authentication occurs only for credentials for the last model.  
For example, if Property model has item with `user_1@example.com` and SuperProperty has `user_2@example.com`, autentication for `user_1@example.com` always will be fail with the `You need to sign in or sign up before continuing.` error message. But for `user_2@example.com` it will be OK.   
And if I will change `acts_as_token_authentication_handler_for` defiitions in reverse order everything will be vice versa - succesfull auth for `user_1@example.com` and error for `user_2@example.com`

**Comment by lemboy** [comment]
I have a workaround now.

```
    acts_as_token_authentication_handler_for ::SuperProperty, if: ->(controller) { controller.super_property? }
    acts_as_token_authentication_handler_for ::Property, unless: ->(controller) { controller.super_property? }
```

**Comment by gonzalo-bulnes** [comment]
Hi @lemboy,

I'm sorry, I didn't see you update. (I was putting together this [wiki page][ask] to ask you more information.) But with your update I know enough to know what happens.

_Simple Token Authentication_ falls back to Devise authentication by default, that's why if your `SuperProperty` token authentication fails, Devise take things in hand (and fails) before token authentication for `Property` is ever attempted.

The relevant documentation is [here][doc] (sorry, I didn't find any way to highlight a section of the `README` in its [rendered form][rendered]). Note that since then, the `fallback: :none` syntax was introduced and is preferred to `fallback_to_devise: false`.

Unless I'm missing something in your context, the following refactoring should be possible:

```ruby
module Properties
  class Api::V1::TransfersController < Api::V1::ApplicationController

    acts_as_token_authentication_handler_for ::SuperProperty, fallback: :none
    acts_as_token_authentication_handler_for ::Property

    # ...
  end
end
```

  [doc]: https://github.com/gonzalo-bulnes/simple_token_authentication/commit/414764bdb5a5cb5b23f202f249b8699bf0df3648
  [rendered]: https://github.com/gonzalo-bulnes/simple_token_authentication#allow-controllers-to-handle-token-authentication
  [ask]: https://github.com/gonzalo-bulnes/simple_token_authentication/wiki/Asking-for-help

**Comment by gonzalo-bulnes** [comment]
Also, if you don't intend your `Api::V1::TransfersController` action to be acceded authenticating via Devise strategies, you can skip the Devise fallback by making token authentication required with:


```ruby
module Properties
  class Api::V1::TransfersController < Api::V1::ApplicationController

    acts_as_token_authentication_handler_for ::SuperProperty, fallback: :none
    acts_as_token_authentication_handler_for ::Property, fallback: :exception

    # ...
  end
end
```

**Comment by lemboy** [comment]
Hello, @gonzalo-bulnes!  
  
Many thanks! I will check if it helped me.

**Comment by antonivanopoulos** [comment]
Hey @gonzalo-bulnes!

Seem to be having a similar issue. Where I have two different user types configured along the lines of:
```
class Api::V1::BaseController < ApplicationController
    acts_as_token_authentication_handler_for ::Supplier, fallback: :none
    acts_as_token_authentication_handler_for ::Customer, fallback: :exception
end
```
Passing in the credentials for a `Supplier` will still result in a 401. If it handles authentication for a `Supplier` does it still attempt authentication for a `Customer`? (In which case the token isn't there for a `Customer`, so would throw an exception)

**Comment by gonzalo-bulnes** [comment]
Yes @antonivanopoulos, you're right, at the end it's only a couple of `before_action`s. I'm thinking aloud, and might be wrong, but it may be possible to do something in the lines of:

```ruby
class Api::V1::BaseController < ApplicationController
    acts_as_token_authentication_handler_for ::Supplier, fallback: :none
    acts_as_token_authentication_handler_for ::Customer, fallback: :exception, if: lambda { |controller| current_supplier.nil? }
end
```

**Comment by dowi** [comment]
@gonzalo-bulnes this worked for me. does this mean the documentation in the readme is incorrect?

**Comment by dowi** [comment]
sure! but say, in the readme you have 3 models. will you need to do the same process in the second acts_as_token_authentication_handler_for as well or only on the last instance?
(i dont have 3 models to test now)
thanks!
