### ISSUE TITLE
Best strategy for Web Sign In. Cookie authentication method.

### ISSUE THREAD

**Issue by oscarsiniscalchi** [gonzalo-bulnes/simple_token_authentication#244]
I have used this gem for a few months on an API backend project that serves data to a iOS and an Android frontends.
The gem is great, I had to do some changes to work around some technical requirements I had: my login goes against an external API I do not control, so I basically get the login request, check the external API, if the login success, I regenerate the Auth token and return that to the mobile clients to include on any request that needs authentication. Just recently we have decided to add a web frontend for the same app, so I decided to build the authentication for this new front end the similar to how it works for mobile clients > I make the login via ajax and on success store the auth token-email pair in a cookie so I can send in future auth requests.
However what I am struggling with at the moment is, after the user is signed in let say I do a GET request to `/user/profile` how do I authenticate the user here? do I mandatory need to send the auth pair via get parameters? is there a better way to do this you guys could think of?
Wouldn't be good to be able to also support authentication method from cookies? can you think of a disadvantage of supporting the latest?

I would much appreciate your input and advice on this one since I want to try to build this on the cleanest way possible.

Regards

**Comment by gonzalo-bulnes** [comment]
Hello @oscarsiniscalchi,

The **sign_in_token** option is meant to be used to create a persiistent session after successful token authentication. It's quite convenient because it delegates the cookies management to the usual Devise mecanism and I think it could match your scenario. (See [the first entry in the configuration documentation][config] for usage details.)

  [config]: https://github.com/gonzalo-bulnes/simple_token_authentication/blob/master/README.md#configuration

Things to be aware of: if you disabled CSRF protection in your API, setting a cookie makes you vulnerable to session fixation attacks. See #49 - it's a long thread, but is worth reading to understand the problem. (Don't hesitate to comment there if anything remains unclear, I can write a wrap ip comment if necessary.)
The issue only appears when the same user is authorized to accede both the non-CSRF-protected controllers (API) and the ones which set cookies (website), but I believe this is your case. (Please confirm!)

If you are willing to discuss possible workarounds, I'd like to find a standard way to support such scenarios.

See also #216

**Comment by gonzalo-bulnes** [comment]
I'm changing labels to redirect the main discussion to #216.
