### ISSUE TITLE
test failures

### ISSUE THREAD

**Issue by davideghz** [gonzalo-bulnes/simple_token_authentication#249]
Hi, sorry if I ask something basic, but I can't successfully test auth with token; I always get a `Expected response to be a <success>, but was <302>`

I filled the test database with a dummy user, and I passed to the @request.headers and to the query params actual values, but still my test fails.

Any clue?

**Comment by gonzalo-bulnes** [comment]
Hello @davideghz,

Can you please check #202 and reopen it if it matches your scenario? (Keeping similar issues in the same thread helps finding answers in the closed questions.)

I replied there about making sure that the authentication token was set as part of the test setup, (but got no feedback since). It's something I think you should check.

If it doesn't seem to be the cause of the issue, please provide me with one example test, and the factory your're using (if any) so we can debug it together. See also  [this list of useful information to provide][wiki] in order to make debugging easier - it is not specific to testing issures, but gives an ideas of what are the moving parts of token authentication : )

Last but not least, let me know if anything is unclear and I'll try to put together a similar list for testng issues : )

**Comment by davideghz** [comment]
Hi @gonzalo-bulnes - thank you very much for your reply. Actually I didn't mention I'm using **minitest**, and I think the test logic is slighty different, so issue #202 shouldn't be related.

My token authenticatable model is User.

My application_controller.rb looks like this:

```
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale
  acts_as_token_authentication_handler_for User
end
```

my users_controller_test.rb looks like this:

```
require 'test_helper'

class UsersControllerTest < ActionController::TestCase

  test "index with token authentication via query params" do
    get :index, { user_email: "davideghz@gmail.com", user_token: "oFFuam5QiaiqS7R_zYoZ" }
    assert_response :success
    # assert_response :redirect
  end

  test "index with token authentication via request headers" do
    @request.headers['X-User-Email'] = "davideghz@gmail.com"
    @request.headers['X-User-Token'] = "oFFuam5QiaiqS7R_zYoZ"

    get :index
    assert_response :success
    # assert_response :redirect
  end

end
```

Both tests fail, and I get ` Expected response to be a <success>, but was <302>`.

**Comment by gonzalo-bulnes** [comment]
Hi @davidegz,

Can you show me how you are creating the user in the **test** database?

First of all you need to make sure that an user exists there, that it has an email and an authentication token, and that both are the same you are using in your tests. - It may seem obvious, but it's easy to miss.

**Comment by davideghz** [comment]
Hi @gonzalo-bulnes,
I create users through the seed.rb file

```
# Users
user = User.new(email: "davideghz@gmail.com",
                password: "12345678")
user.skip_confirmation! # it sets confirmed_at: DateTime.now
user.save!
```

The presence of the authentication_token is assured by the user.save! and by the after_save filter that the gem should add, right?

Then I look into the test.sqllite3 DB, copy the authentication_token and paste it into the test block as above.

**Comment by gonzalo-bulnes** [comment]
Ok. The process seems a bit complex to me, but it still seems fine. At least the following is correct:

> The presence of the authentication_token is assured by the user.save! and by the after_save filter that the gem should add, right? 

Just to be sure that nothing fancy happens between the time you check your test database and the time the test is runned, could you temporary add a couple of assertions to it? I'm thinking in something like:

```ruby
# users_controller_test.rb

require 'test_helper'

class UsersControllerTest < ActionController::TestCase

  test "index with token authentication via query params" do
    get :index, { user_email: "davideghz@gmail.com", user_token: "oFFuam5QiaiqS7R_zYoZ" }
    
    # temporary:
    assert_equal("davideghz@gmail.com", user.email, "The test user doesn't have the email we thought it would!")
    assert_equal("oFFuam5QiaiqS7R_zYoZ", user.authentication_token, "The test user doesn't have the token we thought it would!")

    assert_response :success
  end

  # ...
end
```

Unrelated note: _I would also suggest that at some point (not necessarily now) you create the test user before each of your tests. That would allow you to use arbitrary credentials (e.g. `"alice@example.com"`, `"1G8_s7P-V-4MGojaKD7a"`) and would make the process of writing new test considerably simpler for you. I'm not familiar with Minitest, but I guess the [`setup`][setup] method is probably a good place to start._

  [setup]: http://ruby-doc.org/stdlib-2.0.0/libdoc/minitest/rdoc/MiniTest/Unit/TestCase.html#method-i-setup


**Question**: Is token authentication already setup and working or are you test-driving it? I just want to understand the context and confirm that we're looking after a testing-specific bug, as I think we are. : )

**Comment by davideghz** [comment]
Hello again, and thank you very much for your time and support!

The token auth is already setup and working.

Actually I do not have a test user, I just try to make the json call, passing what should be valid user parameters (they are valid because they exist in the test DB).

If I add the code you suggest I got an error:

```
NameError: undefined local variable or method `user' for #<UsersControllerTest:0x00000004d787b0>
    test/controllers/api/v1/users_controller_test.rb:9:in `block in <class:UsersControllerTest>'

```

**Comment by gonzalo-bulnes** [comment]
Yes, because there is not `user` in the test.

```ruby
# users_controller_test.rb

require 'test_helper'

class UsersControllerTest < ActionController::TestCase

  test "index with token authentication via query params" do
    get :index, { user_email: "davideghz@gmail.com", user_token: "oFFuam5QiaiqS7R_zYoZ" }
    
    # temporary:
    user = User.find_by(email: "davideghz@gmail.com")
    refute_nil(user, "The test user doesn't have the email we thought it would!")
    assert_equal("oFFuam5QiaiqS7R_zYoZ", user.authentication_token, "The test user doesn't have the token we thought it would!")

    assert_response :success
  end

  # ...
end
```

See [`refute_nil`](http://ruby-doc.org/stdlib-2.0.0/libdoc/minitest/rdoc/MiniTest/Assertions.html#method-i-refute_nil) for details, but that's the same idea as before: making sure that the user we're trying to authenticate in the test is defined in the test database.

**Comment by davideghz** [comment]
Hello,

`refute_nil` and `assert_equal` pass the test, but still I got failures on `assert_response :success`

  1) Failure:
UsersControllerTest#test_index_with_token_authentication_via_query_params [/.../test/controllers/api/v1/users_controller_test.rb:13]:
Expected response to be a <success>, but was <302>

  2) Failure:
UsersControllerTest#test_index_with_token_authentication_via_request_headers [/.../test/controllers/api/v1/users_controller_test.rb:22]:
Expected response to be a <success>, but was <302>

I think it's not related to the presence of a user in test DB, because I manually seeded the test DB myself, so I'm sure the records are there!

**Comment by gonzalo-bulnes** [comment]
Oh, wait HTTP 302 is a redirection! I'm sorry I didn't notice that until now.
I believe that redirection is part of the Devise behaviour, does [disabling the Devise redirection](https://github.com/plataformatec/devise/wiki/How-To%3A-Redirect-to-a-specific-page-on-successful-sign-in-and-sign-out) help?

```ruby
# app/controllers/application_controller.rb

def after_sign_in_path_for(resource)
  request.referrer
end
```

(See also the [official documentation for the `after_sign_in_path` hook](http://www.rubydoc.info/github/plataformatec/devise/master/Devise/Controllers/Helpers:after_sign_in_path_for).)

**Comment by gonzalo-bulnes** [comment]
By the way, good for the user in the test DB! 👍

**Comment by davideghz** [comment]
Unfortunately it doesn't work; I open a SO question - http://stackoverflow.com/questions/36986149/rails-minitest-json-api-get-index-always-redirect-me

**Comment by davideghz** [comment]
I played with it and it seems the key is that test user is not logged in. If I remove `assert_response :success` and I put `p response.body` instead, I get the following output:

"<html><body>You are being <a href=\"http://test.host/users/sign_in\">redirected</a>.</body></html>"

If I remove the `acts_as_token_authentication_handler_for User` from application_controller.rb, then the test user is not redirected and tests pass.

So I think the problem lies in

`get :index, { user_email: user.email, user_token: user.authentication_token }`

which is not loggin-in the user.

Am I missing something?

**Comment by gonzalo-bulnes** [comment]
If your request is being redirected to the signin form, then you should take a look at the [**Troubleshooting**](https://github.com/gonzalo-bulnes/simple_token_authentication/wiki/Unexpected-HTTP-401-Errors) section of the wiki because there is probably a misplaced Devise callback in your `UsersController` (I'm assuming its in the `UsersController` because I don't see any in your `ApplicationController`.) But I would be surprized because it's something you would also notice when trsting manually:

> The token auth is already setup and working.

I'm just wondering:

> I just try to make the json call, passing what should be valid user parameters

Are you restricting token authentication to JSON requests? (I don't see such restriction anywhere in the code you submitted, but I'm looking for what I could have missed.) Unless I'm missing something the test requests don't seem to be JSON requests.

**Comment by davideghz** [comment]
Hi @gonzalo-bulnes - I just got a clue:

I moved `acts_as_token_authentication_handler_for User` from `application_controller` to `api/v1/users_controller` (this is mainly to allow users to see standard pages w/o requiring authentication) and added the `fallback: :none` option and it works.

Anyway I don't think I've disabled CSRF protection; my application_controller still have:
`protect_from_forgery with: :null_session`

Can you pls enlight me and tell me why now it works? :)

**Comment by davideghz** [comment]
Hello, can you pls give me some inputs or pointing me to some resources I can use to better understand? Thank you!

**Comment by gonzalo-bulnes** [comment]
Hi @davideghz,

The reference issue for CSRF-related security risks is #49. You'll also find pointers to CSRF-related litterature in #37.

**In a nutshell**: API often disable CSRF protection. If you do so, you want to make sure that you don't fall back to cookie-based Devise strategies when token authentication fails (_i.e._ make sure you use `fallback: :none` or `fallback: :exception` because the default `fallback: :devise` is not safe in these conditions). Please let me know in #49 if anything remains unclear : )
