### ISSUE TITLE
Trouble with integrating with omniauth

### ISSUE THREAD

**Issue by jamesfzhang** [gonzalo-bulnes/simple_token_authentication#250]
I am using this gem just fine for my app's API endpoints (thanks for creating it!). However, I am running into trouble when integrating with omniauth.

This is the callback for OAuth with SoundCloud.

```ruby
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  acts_as_token_authentication_handler_for User, fallback: :devise

  def soundcloud
    @user = User.from_soundcloud_omniauth(env['omniauth.auth'])
    sign_in_and_redirect @user, event: :authentication
  end
end
```

In this callback, `current_user` is nil since neither user ID or the authentication token is present as a header or query param.

Here's an example of the callback URL:

`http://localhost:5000/users/auth/soundcloud/callback?code=121ee49287ff75bae7c379a5e7c3af8b&state=a4a18f12d48d78a72b5b50ea21309642e453fb1319abff3a`

How would you authenticate the user in this scenario? Thanks!

**Comment by gonzalo-bulnes** [comment]
Hello @jamesfzhang,

If I understand correctly, you authentication your API requests using token authentication, and would lije to authenticate some webapp requests via OmniAuth. (If I'm wrong, please see [this wiki page][wiki] for details about providing more context.)

OmniAuth and token authentication are two different strategies and play a similar role in authenticating your users. That means that if your users are authenticated via OmniAuth, they don't need to be authenticated via token authentication too.

Your OmniAuth callback seems to be failing because the SoundCloud request lacks authtication credentials, as you have noted. But SoundCloud is not an user, and its requests are authenticated via mechanisms included in the OmniAuth proticols, you don't need to add a token authentication guard for them.

To stop requiring token authentication for a specific controller or controller action, you can use the **except** option, but in this case I think you can just remove the `acts_as_token_autbentication_handler_for User` (note that `fallback: :devise` is the default) from your `User::OmniauthCallbacksController`.

**Comment by jamesfzhang** [comment]
Hi @gonzalo-bulnes thank you for your detailed reply. I understand now. What I am looking for is to connect a logged-in user with his/her SoundCloud account. In that case, since the user is already logged in, I just removed the `acts_as_token_autbentication_handler_for` action and fixed the problem. Thank you!

**Comment by gonzalo-bulnes** [comment]
You're welcome @jamesfzhang!
