### ISSUE TITLE
Use with route constraints which rely on the current user

### ISSUE THREAD

**Issue by richardonrails** [gonzalo-bulnes/simple_token_authentication#251]
I'm attempting to include simple_token_authentication into a Rails app but am currently getting a 404 when going to my routes and attempting authentication like:

`https://example.com/sites/1/articles.json?user_email=info@example.com&user_token=XXXX`

This issue seems to be my route constraint - which works fine with normal Devise authentication, but not with simple_token_authentication. If I remove my route constraint, both works fine.

How can I achieve the same result as I do currently with my route constraints, but also have it work with token auth?

My routes look like:

```ruby
  constraints RoleConstraint.new(:admin) do
    resources :sites do
      resources :articles
    end
  end
```

The constraint:

```ruby
# From https://gist.github.com/yesmeck/7060244
class RoleConstraint
  def initialize(*roles)
    @roles = roles.map { |r| r.to_s }
  end

  def matches?(request)
    @roles.include? request.env['warden'].user(:user).try(:role)
  end
end
```

Model:

```ruby
class User < ActiveRecord::Base
  acts_as_token_authenticatable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: [:admin, :read_only]
end
```

Controller:

```ruby
class ApplicationController < ActionController::Base
  acts_as_token_authentication_handler_for User
  protect_from_forgery with: :exception
  # ...
end
```

**Comment by gonzalo-bulnes** [comment]
Hello @richardonrails,

I am not very familiar with routes constraints, but I believe that the constraint checking fails to find an user (hence an `:admin` user) because it is performed _before_ token authentication is performed.

**Question**: if you disable the token authentication and use only your regular Devise strategies, what happens if you try to visit that URL _with no user signed in_? Do you get the same HTTP 404 response?

Unless I'm wrong, when an user is already signed in, their session can be retrieved by Warden and their role can be checked by the route constraint. But if no user is signed in, then there is no Warden user, and there is no role to check in the constraint - hence the check fails and ends in a HTTP 404 response. If that is correct, then I don't think you can take benefit of a route constraint which relies on the current user when using token authentication. (I might be wrong, however - please let me know what happens with no users signed in!)

**Comment by richardonrails** [comment]
Yes, the route constraint yields to a 404 on unauthenticated requests even without the the auth token.

I guess my question was: is there a way to make the token authentication happen earlier in the process, like Warden does, so that it could be used with route constraints?

You may have already answered this with a "no", but just double checking...

**Comment by gonzalo-bulnes** [comment]
Hi @richardonrails,

While there are ways to perform token authentication at the middleware level (that's to say before the request even hits the Rails app) with Warden, I personally wouldn't go that way - mainly because I think that it is not worth trying to go without the [`Devise.secure_compare`][compare] function.

About alternatives to route constraint for authorization, [CanCanCan][ccc] (f.k.a CanCan) and [Pundit][pundit] are probably the most popular. But  [there are a few others that I don't know][rtb] and even options to check permissions at a very granular level, like [Protector][protector].

All these rely on pretty much the same requirement: some kind of authentication (read a `current_user`) at the controller level which Devise and _Simple Token Authentication_ can provide you. And yes, all these are somewhat equivalent to adding a `before_action` in your controllers.

I hope that help!

  [compare]: https://github.com/gonzalo-bulnes/simple_token_authentication/blob/v1.13.0/lib/simple_token_authentication/token_comparator.rb#L14-L18
  [rtb]: https://www.ruby-toolbox.com/categories/rails_authorization
  [ccc]: https://github.com/CanCanCommunity/cancancan
  [pundit]: https://github.com/elabs/pundit
  [protector]: https://github.com/inossidabile/protector

**Comment by gonzalo-bulnes** [comment]
**Note**: I edited slightly the issue title to make it more precise.
