### ISSUE TITLE
Can't sign up use this gem keeps 401 error

### ISSUE THREAD

**Issue by williamhqs** [gonzalo-bulnes/simple_token_authentication#267]
I am working on Rails 5 with api project, but i can't register user.

curl -d "email=bob@gmail.com&password=12345678&password_confirmation=12345678" "http://localhost:3000/users/sign_in" 

i got error:

**Started POST "/users/sign_in" for ::1 at 2016-08-30 15:34:08 +0800
Processing by Devise::SessionsController#create as application/vnd.auroma.v1
Completed 401 Unauthorized in 1ms (ActiveRecord: 0.0ms)
You need to sign in or sign up before continuing.**

I am not sure where am i wrong, thanks for your help.

**application_controller.rb**
```

class ApplicationController < ActionController::API
  skip_before_action :authenticate_user!, raise: false
  acts_as_token_authentication_handler_for User, fallback: :none 
end
```

**Comment by gonzalo-bulnes** [comment]
Hello @williamhqs,

Signing up users is out of the field of token authentication (once users are created and can sign in, then they can use token authentication to do it).

I would redirect you to the Devise documentation and recommend you first become familiar using the Devise API to sign up (sending an _email_, _password_ and *password_confirmation*) **then** sign in users (sending their _email_ and _password_) though the API. When you're at this stage is where _Simple Token Authentication_ kicks in, to allow you users to sign in without sending their password, but a renewable _authentication token_ instead (along with their _email_).

The `README` may be a bit too short on that, but setting up Devise is a pre-requisite and I strongly recommend taking separate steps, first Devise _database authentication_, then _token authentication_ with this gem, otherwise things can quickly become very confusing.

To get you started on the Devise setup, I notice a few things in your current setup: you are trying to _register_ (sign _up) an user, and sending email, password and password condirmation is consitent with that. Yet unless I'm wrong sign up happens at `/users/sign_up`?

**Comment by williamhqs** [comment]
Hi @gonzalo-bulnes Thank you for your reply on time. I understood now and it's my bad i think the register should be `/user` path. Sorry for this, thank you for your good work. Feel free to delete this issue :)
