### ISSUE TITLE
skip `acts_as_token_authentication_handler_for` 

### ISSUE THREAD

**Issue by sandeep45** [gonzalo-bulnes/simple_token_authentication#268]
In `ApplicationController` I have `acts_as_token_authentication_handler_for User`

Is there a way to skip `acts_as_token_authentication_handler_for` in a controller which inherits from `ApplicationController`.

**Comment by gonzalo-bulnes** [comment]
Hello @sandeep45,

Not at this point, officially. The dea would be only enabling support for token authentication in controllers that actually support it (`ApplicationController` is merely used as an example in the documentation).

In a given controller, conditional token authentication can be defined using the `if`, `unless`, `only`, `except` options. (Examples can be found in [this section of the docs](https://github.com/gonzalo-bulnes/simple_token_authentication/blob/master/README.md#allow-controllers-to-handle-token-authentication).)

In practice, `acts_as_token_authentication_for` does define two ActionController callbacks ([source](https://github.com/gonzalo-bulnes/simple_token_authentication/blob/v1.14.0/lib/simple_token_authentication/token_authentication_handler.rb#L122-L139)), that you could skip as you skip any other ActionController callback, but the name of these callbacks is not part of the public API of the gem. That's why I would recommend not depending on them and do what I suggested in the first paragraph instead.

I hope this helps : )
Keep me updated!

**Comment by sandeep45** [comment]
@gonzalo-bulnes thanks for input. I have updated my `ApplicationController` to use an `except` on `acts_as_token_authentication_handler_for `. This would work for now. If things get too crazy I'll take your advice and move the `acts_as_token_authentication_handler_for` into individual controllers.

**Comment by gonzalo-bulnes** [comment]
Awesome! I'll close the issue, don't hesitate to re-open it if things get too crazy at some point : )

**Comment by jpmermoz** [comment]
I know this is a closed issue, but I figured it out like this:

In `ApplicationController`:

`acts_as_token_authentication_handler_for User, unless: :no_authentication_required`

`def no_authentication_required`
    `self._process_action_callbacks.map {|c| c.filter }.compact.include? :no_authentication_required`
 `end`

Then, in the controller I want to skip authentication, I use:

`
before_action :no_authentication_required
`

**Comment by AlexVPopov** [comment]
@gonzalo-bulnes first of all, thank you for the gem. 

I think it is quite to common pattern that in a top level controller (be it `ApplicationController` or a custom `ApiController`), one has a callback for authenticating a user (like Devise's `authenticate_user!`), which is then skipped in a `SigninController`/`SessionsController` or any other controller, which contains public actions. Don't you think it makes more sense to have authentication by default and skipping it for public controller actions, instead of having to add authentication to each and every single controller in an API? Or was there a special reason for the current implementation?

**Comment by subelsky** [comment]
I was also confused by this - I expected it to work just like any other authentication filter. I need it everywhere in the app I'm working on except for one particular action in one controller

**Comment by Startouf** [comment]
@gonzalo-bulnes should this tocket be re-opened ? From a security point of view it's also better to have authentication enabled by default :/

**Comment by mikemerritt** [comment]
@gonzalo-bulnes I agree with those above. The best practice is to authenticate by default and skip authentication for non-secure controllers.

**Comment by giovannibonetti** [comment]
I'll post here what I have done in the project I'm working at now since it might me useful to other people. My solution is similar to [@jpmermoz's](https://github.com/gonzalo-bulnes/simple_token_authentication/issues/268#issuecomment-278122256) but has the added benefit of working with Devise's `before_action :authenticate_user!`

### Problem
Retrofitting existing controllers with HTML and JS views to produce JSON output without touching controllers, only adding JSON views. Devise is used for regular authentication, with calls to `authenticate_user!` in some of them indicating which actions need authentication.
In this application most actions require authentication, so there is a `before_action :authenticate_user!` in `ApplicationController` and a few calls like `skip_before_action :authenticate_user!, only: [:foo, :bar]` in some controllers (that inherit from `ApplicationController`

### Solution

Here is what I have applied in `ApplicationController` to make the existing controllers authenticate either via token in headers (JSON) or traditional cookies (HTML and JS).

```ruby
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # http://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection.html
  protect_from_forgery with: :exception, unless: -> { request.format.json? }
  protect_from_forgery with: :null_session, if: -> { request.format.json? }

  # "acts_as_token_authentication_handler_for" should be placed after "protect_from_forgery"
  # https://github.com/gonzalo-bulnes/simple_token_authentication/issues/49#issuecomment-314146831
  acts_as_token_authentication_handler_for User, if: :authentication_required?

  # "authenticate_user!" should be placed after "acts_as_token_authentication_handler_for"
  before_action :authenticate_user!

  protected

  # apply to token authentication the same policy
  # that is already implemented in the rest of the app
  # with the default Devise authentication (cookies)
  # with "before_action :authenticate_user!"
  def authentication_required?
    authentication_callback.present? &&
      authentication_callback
        .instance_variable_get('@if')
        .all? { |callable| callable.call(self) } &&
      authentication_callback
        .instance_variable_get('@unless')
        .none? { |callable| callable.call(self) }
  end

  # ugly hack but works like a charm in Rails 5.1
  def authentication_callback
    @authentication_callback ||= _process_action_callbacks.find do |callback|
      callback.instance_variable_get('@key') == :authenticate_user!
    end
  end
end
```

**Comment by goelinsights** [comment]
@jpmermoz thank you. Perfect approach for a Rails API implementation needing to create an exception for the sessions controller, but otherwise enforce login and enforce a tenant scope (this I pass into the Thread).
