### ISSUE TITLE
Hault on 401 Unauthorized

### ISSUE THREAD

**Issue by pwgustafson** [gonzalo-bulnes/simple_token_authentication#280]
Hello, I recently started using the gem, thanks for contributing this!

I have searched all the docs and wiki, and can't seem to figure out a small issue I am having.  When an invalid email/token are provided, I don't seem to get a 401 unauthorized response code.  Because I am using devise, it seems to fall back on `authenticate_user!` which I believe is the desired action, but for my API requests I would like to just hault the response and return a `401 unauthorized`.

pages_controller.rb
```
class Api::PagesController < Api::BaseController
  acts_as_token_authentication_handler_for User
end
```

user.rb
```
class User < ApplicationRecord
  acts_as_token_authenticatable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end
```

Log File
```
Started POST "/api/pages" for 127.0.0.1 at 2016-11-09 17:18:21 -0800
Processing by Api::PagesController#create as */*
  Parameters: {}
  User Load (2.5ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["email", "no@no.coms"], ["LIMIT", 1]]
**Completed 401 Unauthorized in 6ms (ActiveRecord: 2.5ms)**


Started GET "/users/sign_in" for 127.0.0.1 at 2016-11-09 17:18:22 -0800
Processing by Devise::SessionsController#new as */*
  Rendering devise/sessions/new.html.haml within layouts/application
  Rendered devise/shared/_links.html.haml (3.6ms)
  Rendered devise/sessions/new.html.haml within layouts/application (10.7ms)
Completed 200 OK in 54ms (Views: 51.4ms | ActiveRecord: 0.0ms)
```

I see the 401 Unauthorized in the first response, but how would I cause the request to just stop there and not continue on to the `Devise::SessionsController`  I would like all API request to simply return a 401 response code if there is ever invalid credentials provided.

Thanks again for a great tool, really appreciate it!

**Comment by gonzalo-bulnes** [comment]
Hi @pwgustafson,

Take a look at https://github.com/gonzalo-bulnes/simple_token_authentication/issues/154,  `fallback: :exception` is what you are looking for.

**Comment by pwgustafson** [comment]
Thanks @gonzalo-bulnes 

I thought that was what I needed, but when I include that, I still see the same result...

Versions:
Rails 5.0.0.1
ruby 2.3.1p112
simple_token_authentication (1.14.0)

**Comment by gonzalo-bulnes** [comment]
Hi @pwgustafson,

What client are you using? Your logs show two requests: `POST "/api/pages"` which gets a HTTP 401 as a response, and then `GET "/users/sign_in"` which is actually a second request.

Couldn't that be a "feature" of your client? (If the access is denied I follow up asking for the sign in page...) I'm asking because that doesn't look like a redirect, but an independent request...

Being two independent requests, the behaviour you describe is expected (you'll always get the Devise authentication page if your client asks for it, and the request to other pages will be denied if they're set up to require authentication - `acts_as_token_authentication_handler_for User, fallback: :exception`.)

**Comment by pwgustafson** [comment]
Thanks @gonzalo-bulnes 

Yes, I was testing using Postman, so it looks like that could be the client making the second request.  I was hoping there was a way to halt that second request with the `fallback: :exception` but maybe that is a devise thing.

Anyway, thanks again!
