### ISSUE TITLE
Jbuilder not rendering view in rails API after device install

### ISSUE THREAD

**Issue by IvRRimum** [gonzalo-bulnes/simple_token_authentication#286]
It was working before. But after i installed devise and simple_token_authentication, it just shows blank page.

Heres what rails logs show:
```
Started GET "/home.json" for 85.254.182.95 at 2017-01-15 15:03:51 +0200
Processing by HomeController#index as JSON
Completed 200 OK in 0ms (Views: 0.1ms | ActiveRecord: 0.0ms)


Started GET "/home.json" for 85.254.182.95 at 2017-01-15 15:05:24 +0200
Processing by HomeController#index as JSON
Completed 200 OK in 1ms (Views: 0.1ms | ActiveRecord: 0.0ms)
```

I have a view in `views/home/index.json.jbuilder` ( i tryed renaming it to `index.jbuilder` ).
I tryed to `render "home/index.json.jbuilder"`, i tryed using `respond_to ...`

My gemfile:
```
source 'https://rubygems.org'

gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'sqlite3'
gem 'puma', '~> 3.0'
gem 'jbuilder', github: 'rails/jbuilder'
gem 'dotenv-rails'
gem 'devise'
gem 'simple_token_authentication', '~> 1.0'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'pry'
end

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

if i remove simple_token_authentication jbuilder is working again. Whats the problem?

How to fix this issue?

**Comment by gonzalo-bulnes** [comment]
Hello @IvRRimum,

There is an open issue related to Jbuilder, #278?, do you think this one is related? If this is confirming the issue, could you please highlight any similarity/differences with the details submitted wy @Pepan?

That would be great. Indeed, if there are more similarities than differences, let's move the conversation there, if you think the issue is unrelated, let's keep the conversation separate. Does it make sense?

**Comment by IvRRimum** [comment]
Yeap, same situation as him!
