### ISSUE TITLE
Support for Rails 6+ ?

### ISSUE THREAD

**Issue by MatthiasRMS** [gonzalo-bulnes/simple_token_authentication#346]
Hi,

I'm trying to update my app to Rails 6 but I get this error:
```
    simple_token_authentication was resolved to 1.15.1, which depends on
      actionpack (< 6, >= 3.2.6)
```

Is it planned to update it for Rails 6 ? 
I'd be happy to contribute to the upgrade and submit a PR if you already know what there is to do to maintain the compatibility.

Matthias

**Comment by chevinbrown** [comment]
@MatthiasRMS I'm not involved in the repo at all...but maybe submit a PR that bumps `actionpack (<6.1 ...` with the apprasial/gemfile additions needed and we can start a discussion? 

We'll need this change, so I'm willing to take a look too. Thoughts?

**Comment by oystersauce8** [comment]
Guys can we use this?
https://edgeapi.rubyonrails.org/classes/ActionController/HttpAuthentication/Token.html

**Comment by gonzalo-bulnes** [comment]
Hi @MatthiasRMS, @chevinbrown!

Yes, of course. I'm not aware either of what may have changed in Rails 6, but I'm willing to support you getting this done if you feel like submitting a PR.

I think that @chevinbrown suggestion is a good one: starting by loosening the version constraint in [`simple_token_authentication.gemspec`](https://github.com/gonzalo-bulnes/simple_token_authentication/blob/v1.15.1/simple_token_authentication.gemspec#L19-L25) and adding a Rails 6 test case will likely allow to understand what needs to be done next.

If you look at [how Rails 5 support was added](https://github.com/gonzalo-bulnes/simple_token_authentication/pull/262) (and ignore the first two commits), you'll notice that Rails 5 mostly worked out-of-the-box; the larger part of the work being cleaning up deprecation warnings after the update. Some deprecation warnings are easier to remove than others, we can look at that together if needed.

Last but not least, @oystersauce8 this looks indeed like an interesting update. I packaged Simple Token Authentication when Devise dropped support for token authentication, I personally think it would be a good thing if that feature could make it into Rails soon : )

**Comment by gonzalo-bulnes** [comment]
**Note**: I think this issue is a good candidate for anyone interested in contributing to _Simple Token Authentication_, particularly if you haven't done anything like that before. The goal is well defined, the changes made when Rails 5 support was added can provide guidance, and I have personally learnt a lot from maintining the gem, so I'm happy to support you getting started, putting the pull request together and going through the different steps to release.

Setting up [appraisal](https://github.com/thoughtbot/appraisal) to test multiple combinations of Rails may seem a dauting task. It not as bad as it looks at first, and as with everything else, I'm happy to help with that.

Last but not least, I am not a regular user of Rails myself anymore, and I have a vested interest in getting people who use _Simple Token Authentication_ learning how to improve it. :wink:

**Comment by MatthiasRMS** [comment]
Hey @gonzalo-bulnes thanks for the feedback ! 
I can probably get this PR done. I'll start looking at it later today to see how feasible it is and get back to you. 
It there a better way to communicate with you if we need to do many back and forth ?

**Comment by gonzalo-bulnes** [comment]
Hey @MatthiasRMS, nice!

No hurries, I'll be around. Regarding communication, it depends on what you have in mind for "better".

In general, I find useful to discuss most things in public forums (pull request or issue in Github) because it allows people to follow along and get insight into the thought and decision process. People might jump in today, or might refer to it in a few months. I might, or you. And the code is just there for reference or comments. To that purpose, I usually like to open the PR early, and commit/comment often. We can clean it up together before merging.

Besides, that has the advantage of requiring little time coordination. (I'm currently in the UTC +10:00 time zone, that may be a relevant detail...)

That being said, like [pair programming](https://github.com/gonzalo-bulnes/pair) and I'd love to pair at any point if you wish! :slightly_smiling_face:
