### ISSUE TITLE
Support for resource identifiers different than email (example: login, uuid...)?

### ISSUE THREAD

**Issue by bchase** [gonzalo-bulnes/simple_token_authentication#68]
My `User` class needs to be looked up by `login`, which for me is `email` or `username`. (And my implementation essentially follows [this](https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address).)

Is there a simple way to accomplish this?

Judging by [the devise entity lookup I found](https://github.com/gonzalo-bulnes/simple_token_authentication/blob/3a4f9b46f11cf0e4b960de3bc2a6d3048e8e6049/lib/simple_token_authentication/acts_as_token_authentication_handler.rb#L43), thing's are presently hardcoded to lookup by `email`. If this is something I could submit a PR for, I'd be happy to contribute.

Thanks in advance,
Brad

**Comment by gonzalo-bulnes** [comment]
_Simple Token Authentication_ [v1.8.0][release] is released with support for custom identifiers : )

Thanks again @bchase, @ProGM, @wielinde, @nicolo and @speed-of-light for your contributions and support, it's great help!

  [release]: https://github.com/gonzalo-bulnes/simple_token_authentication/releases/tag/v1.8.0

**Comment by trentclowater** [comment]
I had a requirement to use multiple identifiers to authenticate (`:email` and `:application_id` - used by an API that supports multiple mobile apps, but the users of the apps don't know they are related so will use the same email address if they have more than one installed, and also allows access via a website scoped by subdomains).

simple_token_authentication did everything I required except this, so I created a fork that supports the Devise `authentication_keys` and `request_keys`, in addition to the authentication headers supported by simple_token_authentication. This allows one or multiple identifiers to be used for authentication, as well as request properties (such as subdomain, etc.). 

I think this provides better integration with devise so you can define the authentication identifiers in only one place, if for example you are authenticating using `database_authenticatable` via a website, and simple_token_authentication via an API. Currently to use a different identifier you would have to change the Devise `authentication_keys` to use with `database_authenticatable` and the `config.identifiers` to use with simple_token_authentication. With this fork you only need to use the Devise `authentication_keys`.

Would you be interested in this as a PR?

**Comment by gonzalo-bulnes** [comment]
Hello @trentclowater!

That's great! I'm moving, and may not react very quickly these days, but I think that enhancing the Devise integration is an excellent thing to do, and I would be very interested in your PR.

Best regards!

**Comment by trentclowater** [comment]
@gonzalo-bulnes, just need to finish some of the tests (most are done, have a few left) and add some text to `README.md` . Here's what I have:

- If you do not set `config.identifiers`, `authorization_keys`, or `request_keys`, it will use the default value from Devise (which is `:email`). This results in the same behaviour as currently, it just gets the default directly from Devise instead of from simple_token_authentication.
- If  you set `config.identifiers` and it has a key that matches the model currently being used for authentication, it will use that and operate exactly as it does now. This results in the same behaviour as currently.
- If you  set `config.identifiers`, but there is no key that matches the model currently being used for authentication, it will use `authentication_keys` and `request_keys`, or if they also don't exist it will use the default value from Devise (which is `:email`).

So basically, it will get the value from Devise (thus allowing for multiple authentication keys) unless you explicitly set a value for `config.identifiers` for the model that is being authenticated.

Since all users who are currently using simple_token_authentication will either have a value for `config.identifiers` set, or be using `:email`, they should see no change at all. New users can use `authentication_keys` and `request_keys`, allowing them to use multiple authentication keys if they want, and to not have to worry about keeping the Devise and simple_token_authentication configurations synchronized.

Headers are still used exactly the same way (you can use custom header names, header values are given priority over the param values).

I have also included a deprecation warning when using `config.identifers`, since using `authentication_keys` and `request_keys` basically makes its use redundant and provides some benefits (but nobody wants to have their application break for a minor gem update). All of the `config.identifiers` code should be pretty easy to remove in the future.

**Comment by gonzalo-bulnes** [comment]
Hello @trentclowater,

That sounds great!

Note that you can open the PR before it's done, so we can discuss implementation or testing details there. I could also help you with the tests if necessary.

I'm also thinking that a wiki page explaining how to setup a typical case could be great to have. We can probably write it afterwards from the content of you comments.

I look forward to your PR!
Best!

**Comment by trentclowater** [comment]
Still coming! I have some free time in about a week, so I will try to write the final tests and open the PR then (or just open the PR and ask for some help finishing the tests if my free time runs out).

**Comment by qx** [comment]
I still don't know how to do it?  is there anyone make a conclusion

**Comment by aried3r** [comment]
@trentclowater, do you have your code online somewhere? I could not find it in your fork of this repository. I also have the need for multiple identifiers, like devise already supports, but in simple_token_authentication.

@gonzalo-bulnes, also, since a lot of time has passed, is this somehow already possible? I tried different options in `config.header_names` and `config.identifiers` but it seems there's still only the possibility for one identifier.

For support of old API clients I can't turn on `X-USER-EMAIL` and switch to `X-USER-LOGIN` but have to support both until old API versions are being turned off.

**Comment by gonzalo-bulnes** [comment]
Hi @aried3r,

No news on this front, however, the use case makes a lot of sense, and I'm still happy to help with any PR : )

Indeed, if you feel like opening a new issue to support **multiple** different identifiers, please feel free to do it - it would probably be better than discussing in this closed issue IMHO.

**Comment by trentclowater** [comment]
Hi @aried3r & @gonzalo-bulnes,

I ended up writing a warden strategy to use, but I should still have the code somewhere. Give me a day or so to find it and check it against the current master. I never did finish writing the tests before switching my application to the warden strategy, so someone would have to do that, but when I left it, it was fully complete and working very well.

**Comment by rddm2bb** [comment]
My devise authentication keys are an array. How can I configure that ?
