### ISSUE TITLE
Some errors with namespaced classes. 

### ISSUE THREAD

**Issue by joshblour** [gonzalo-bulnes/simple_token_authentication#83]
I had some trouble using this gem with namespaced classed. 

I think the reason is because the underscore inflector is used throughout the code and converts classes like "Core::User" to 'core/user' which might be invalid syntax.

One example is line 120 of acts_as_token_authentication_handler.rb.
```ruby
      def define_acts_as_token_authentication_helpers_for(entity_class)
        entity_underscored = entity_class.name.singularize.underscore

        class_eval <<-METHODS, __FILE__, __LINE__ + 1
          def authenticate_#{entity_underscored}_from_token
            authenticate_entity_from_token!(#{entity_class.name})
          end
```

Another example might be line 70: `X-#{entity_class.name.singularize.camelize}-Token"`
this would look for a token called `"X-Core::User-Token"` which might not be valid syntax. Not sure...

Anyway, I got it working by using the devise strategy branch and specifying the header names in devise.rb initializer.

Oh, and thanks so much for this gem!!!

**Comment by gonzalo-bulnes** [comment]
Hi @joshblour, @fwidtmann, @ivan-kolmychek!

How have you been? Support for namespaced models may be at sight. In the [`spike-add-models-aliases-option`][spike] branch I added an option to define model aliases. What's the idea?

In your  controllers, when you want to handle token authentication for a namespaced model (let's say `MobileApp::User`), you can now define an alias for it:

```ruby
# app/controllers/application_controller.rb

class ApplicationController < ActionController::Base # or ActionController::API
  # ...

  acts_as_token_authentication_handler_for MobileApp::User, as: :mobile_user

  # ...
end
```

Once that done, you should be able to authenticate them using the `mobile_user_token` and `mobile_user_email` or the `X-MobileUser-Token` and `X-MobileUser-Email` headers. (Tadaa!)

Could anyone (or two or the three) of you give it a try please? I would love to make sure everything is fine in a real application context before shipping it. I look forward for news!

Best regards!



  [spike]: https://github.com/gonzalo-bulnes/simple_token_authentication/pull/162

**Comment by gonzalo-bulnes** [comment]
Hi people,

The **v1.9.0** release is now available, with aliases support for _token authenticatable_ models.

A few words about this solution to the issue:

I didn't really liked the idea of replacing the problematic slashes `/` by underscores `_`, because slashes and underscores have conventionally distinct meanings in Rails. Of course, there is nothing wrong in deciding not to follow one convention or another in our applications as long as that produces no name clashes. As developers, we evaluate the context we work in and following or not that kind of conventions is our call.

What I didn't liked was letting _Simple Token Authentication_ make the decision for us. Often the `_` solution would be just good, but [sometimes][example] it wouldn't.

Aliases allow us to decide, and be explicit about the choices we make, I hope you'll agree.

> Explicit is better than implicit. -- [Tim Peters][pep-20]

 Best regards!

  [example]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/83#issuecomment-59054860
  [pep-20]: http://legacy.python.org/dev/peps/pep-0020/
